import { test, expect, type Page } from '@playwright/test'
import ExcelJS from 'exceljs'
import AxeBuilder from '@axe-core/playwright'

const stock = ['Processor', 'Motherboard', 'Memory', 'Graphics', 'Storage', 'Power supply', 'Case', 'Cooling'].map((component, index) => ({ id: `part-${index}`, name: `${component} test part`, sku: `PART-${index}`, category: component, component, tier: 'Mid', socket: ['Processor', 'Motherboard'].includes(component) ? 'AM5' : '', memoryType: ['Motherboard', 'Memory'].includes(component) ? 'DDR5' : '', stock: 5, minimum: 1, price: 1000 + index * 100, cost: 500 }))
const shop = { name: 'Test Workshop', address: 'Workshop address', phone: '09000000000', email: 'shop@example.com', prefix: 'TEST', footer: 'Thank you.', taxRate: 10, labor: 100, delivery: 50, homeSurcharge: '150', transportBase: '25', transportPerKm: '5', warrantyMonths: '12', warrantyTerms: 'Parts warranty; contact the workshop with your invoice.', cleaning: { Desktop: { Low: '500', Mid: '700', High: '900' }, Laptop: { Low: '600', Mid: '800', High: '1000' } } }
async function setup(page: Page) {
  await page.goto('/login')
  await page.evaluate(({ stock, shop }) => {
    localStorage.clear()
    localStorage.setItem('jbc-rigworks:workspace:v1:admin@example.com', JSON.stringify({ jobs: [], sales: [], expenses: [], inventory: stock }))
    localStorage.setItem('jbc-rigworks:shop-settings:v1', JSON.stringify(shop))
    localStorage.setItem('jbc-rigworks:shop-owner:v1', 'admin@example.com')
    sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: 'admin@example.com', email: 'admin@example.com', name: 'Admin', role: 'admin' }))
  }, { stock, shop })
  await page.goto('/pos')
}
async function customer(page: Page, email = 'customer@example.com') {
  await page.evaluate(email => sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: email, email, name: 'Online customer', role: 'customer' })), email)
  await page.goto('/customer/shop')
}

test('POS itemizes charges, deducts stock, preserves invoices and prints only the invoice', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: 'Add Processor test part', exact: true }).click()
  await page.getByRole('button', { name: 'Increase Processor test part', exact: true }).click()
  await page.getByRole('button', { name: 'Add Desktop deep clean - Low specs', exact: true }).click()
  await page.getByRole('button', { name: 'Review checkout' }).click()
  await page.getByLabel('Customer name', { exact: true }).fill('Jamie')
  await page.getByText('Charges, discount & tax', { exact: true }).click()
  await page.getByLabel('Fulfillment', { exact: true }).selectOption('Delivery')
  await page.getByLabel('Delivery address').fill('Test delivery address')
  await page.getByLabel('Customer contact', { exact: true }).fill('09000000000')
  await page.getByLabel('One-way road distance (km)').fill('5')
  await page.getByLabel('Other charges (PHP)', { exact: true }).fill('25')
  await page.getByLabel('Other charge description').fill('Packing')
  await page.getByLabel('Discount (PHP)', { exact: true }).fill('75')
  await page.getByLabel('Amount received (PHP)', { exact: true }).fill('1000')
  await expect(page.locator('.checkout-totals').last()).toContainText('₱2,860.00')
  await page.getByRole('button', { name: 'Complete sale' }).click()
  const invoice = page.getByRole('dialog').locator('.invoice-document')
  await expect(invoice).toContainText('₱2,860.00')
  await expect(invoice).toContainText('₱1,860.00')
  await expect(invoice).toContainText('Packing')
  await expect(invoice.locator('tbody tr')).toHaveCount(2)
  await page.evaluate(() => { window.print = () => { document.documentElement.dataset.printCalled = 'yes' } })
  await page.getByRole('button', { name: 'Print invoice' }).click()
  expect(await page.evaluate(() => document.documentElement.dataset.printCalled)).toBe('yes')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('#root')).toBeHidden()
  await expect(page.locator('.invoice-print-root')).toBeVisible()
  await expect(page.locator('.invoice-print-root')).toContainText('₱2,860.00')
  await page.emulateMedia({ media: 'screen' })
  await page.keyboard.press('Escape')
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com')!))
  expect(data.inventory[0].stock).toBe(3)
  expect(data.sales).toHaveLength(1)
  expect(data.sales[0].charges.tax).toBe(260)
  await page.goto('/sales')
  await page.getByRole('button', { name: /^Edit TEST-/ }).click()
  await expect(page.getByLabel('Total amount (PHP)')).toHaveCount(0)
  await page.getByLabel('Amount received (PHP)').fill('2860')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByRole('button', { name: /^Invoice TEST-/ }).click()
  await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(2)
  await expect(page.getByRole('dialog').locator('.invoice-total').last()).toContainText('₱0.00')
  await page.keyboard.press('Escape')
  await page.goto('/reports')
  await expect(page.locator('.report-highlight')).toContainText('₱1,600.00')
  await expect(page.getByText('₱260.00', { exact: true })).toBeVisible()
})

test('customer orders use shared stock, remain unpaid, and only show their own invoices', async ({ page }) => {
  await setup(page)
  await customer(page)
  await page.getByRole('button', { name: 'Add Processor test part', exact: true }).click()
  await page.getByRole('button', { name: 'Review checkout' }).click()
  await page.getByRole('button', { name: 'Place local order' }).click()
  await expect(page.getByRole('dialog')).toContainText('Unpaid')
  await expect(page.getByRole('dialog')).toContainText('Pay at workshop')
  await page.keyboard.press('Escape')
  await page.goto('/customer/orders')
  await expect(page.locator('.data-table tbody tr')).toHaveCount(1)
  await customer(page, 'another@example.com')
  await page.goto('/customer/orders')
  await expect(page.getByRole('heading', { name: 'No records yet' })).toBeVisible()
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com')!))
  expect(data.inventory[0].stock).toBe(4)
  expect(data.sales[0].channel).toBe('Online')
  expect(data.sales[0].paid).toBe(0)
})

test('stock presets, compatibility checks, saved builds and checkout handoff work', async ({ page }) => {
  await setup(page)
  await page.goto('/pc-building')
  await page.getByRole('button', { name: /Everyday set/ }).click()
  await page.getByRole('button', { name: 'Select Processor', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Processor from stock' })).toHaveValue('part-0')
  await page.getByRole('button', { name: 'Use component' }).click()
  await expect(page.locator('.budget-total')).toContainText('Mid-spec PC set')
  await expect(page.locator('.budget-total')).toContainText('₱10,800.00')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Save build', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Build details', exact: true }).click()
  await page.getByRole('combobox', { name: 'Saved builds' }).selectOption({ label: 'Everyday set' })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Select Processor', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Processor from stock' })).toHaveValue('part-0')
  await page.getByRole('button', { name: 'Use component' }).click()
  await page.getByRole('button', { name: 'Order PC set' }).click()
  await expect(page).toHaveURL(/pos$/)
  await expect(page.locator('.cart-line')).toHaveCount(8)
  await page.goto('/pc-building')
  await page.evaluate(() => {
    const key = 'jbc-rigworks:workspace:v1:admin@example.com'
    const data = JSON.parse(localStorage.getItem(key)!)
    data.inventory[1].socket = 'AM4'
    localStorage.setItem(key, JSON.stringify(data)); window.dispatchEvent(new Event('jbc-workspace-change'))
  })
  await page.getByRole('button', { name: 'Select Processor', exact: true }).click()
  await page.getByRole('combobox', { name: 'Processor from stock' }).selectOption('part-0')
  await page.getByRole('button', { name: 'Use component' }).click()
  await page.getByRole('button', { name: 'Select Motherboard', exact: true }).click()
  await page.getByRole('combobox', { name: 'Motherboard from stock' }).selectOption('part-1')
  await page.getByRole('button', { name: 'Use component' }).click()
  await expect(page.getByText('CPU and motherboard sockets do not match.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Order selected parts' })).toBeDisabled()
  await page.getByRole('button', { name: 'Select Motherboard', exact: true }).click()
  await page.getByRole('combobox', { name: 'Motherboard from stock' }).selectOption('')
  await page.getByRole('button', { name: 'Use component' }).click()
  await expect(page.getByRole('button', { name: 'Order selected parts' })).toBeEnabled()
})

test('simultaneous checkouts cannot oversell the last stock unit', async ({ page, context }) => {
  await setup(page)
  await page.evaluate(() => {
    const key = 'jbc-rigworks:workspace:v1:admin@example.com'
    const data = JSON.parse(localStorage.getItem(key)!)
    data.inventory[0].stock = 1
    localStorage.setItem(key, JSON.stringify(data)); window.dispatchEvent(new Event('jbc-workspace-change'))
  })
  const second = await context.newPage()
  await second.goto('/login')
  await second.evaluate(() => sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: 'admin@example.com', email: 'admin@example.com', name: 'Admin', role: 'admin' })))
  await second.goto('/pos')
  for (const tab of [page, second]) {
    await tab.getByRole('button', { name: 'Add Processor test part', exact: true }).click()
    await tab.getByRole('button', { name: 'Review checkout' }).click()
    await tab.getByLabel('Customer name', { exact: true }).fill('Last unit buyer')
  }
  await Promise.all([page.getByRole('button', { name: 'Complete sale' }).click(), second.getByRole('button', { name: 'Complete sale' }).click()])
  await expect.poll(async () => page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com')!).sales.length)).toBe(1)
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com')!))
  expect(data.inventory[0].stock).toBe(0)
  await expect.poll(async () => (await page.getByRole('alert').count()) + (await second.getByRole('alert').count())).toBe(1)
  await second.close()
})

test('settings persist separate device prices and account preferences', async ({ page }) => {
  await setup(page)
  await page.goto('/settings')
  await page.getByRole('button', { name: /Deep-clean price catalog/ }).click()
  await page.getByLabel('Desktop low specs (PHP)').fill('450')
  await page.getByLabel('Laptop low specs (PHP)').fill('650')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Display name', { exact: true }).fill('Workshop Owner')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await page.getByRole('button', { name: /Display & account access/ }).click()
  await page.getByLabel('Reduce animations').check()
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByRole('status')).toContainText('Settings saved')
  await expect(page.locator('.app-shell')).toHaveClass(/reduce-motion/)
  await page.goto('/customer/services')
  await customer(page)
  await page.goto('/customer/services')
  await expect(page.locator('.service-price-card').nth(0)).toContainText('₱450.00')
  await expect(page.locator('.service-price-card').nth(3)).toContainText('₱650.00')
  await customer(page)
  await page.goto('/customer/settings')
  await expect(page.getByLabel('Desktop low specs (PHP)')).toHaveCount(0)
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Display name', { exact: true }).fill('My Customer Name')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await page.reload()
  await expect(page.locator('.profile-card')).toContainText('My Customer Name')
  await page.goto('/customer/pc-identifier')
  for (const [component, model, field, value] of [['Processor', 'Owned CPU', 'Physical CPU cores', '8'], ['Memory', 'Owned RAM', 'RAM capacity (GB)', '32'], ['Graphics', 'Owned GPU', 'Dedicated graphics memory (GB)', '12']]) {
    await page.getByRole('button', { name: 'Select ' + component, exact: true }).click()
    await page.getByLabel(component + ' from stock').selectOption('__custom')
    await page.getByLabel(component + ' model', { exact: true }).fill(model)
    await page.getByLabel(field, { exact: true }).fill(value)
    await page.getByRole('button', { name: 'Use component' }).click()
  }
  await expect(page.locator('.budget-total')).toContainText('High-spec PC set')
  await page.getByRole('button', { name: 'Select Graphics', exact: true }).click()
  await page.getByLabel('Dedicated graphics memory (GB)', { exact: true }).fill('0')
  await page.getByRole('button', { name: 'Use component' }).click()
  await expect(page.locator('.budget-total')).toContainText('Low-spec PC set')
})

test('exports are readable Excel files with numeric values and frozen headers', async ({ page }) => {
  await setup(page)
  await page.goto('/inventory')
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export Excel' }).click()
  await expect(page.getByRole('dialog', { name: 'Excel preview' })).toBeVisible()
  await page.getByRole('button', { name: 'Download Excel' }).click()
  const download = await pending
  expect(download.suggestedFilename()).toBe('inventory.xlsx')
  const workbook = new ExcelJS.Workbook()
  await workbook.xlsx.readFile((await download.path())!)
  const sheet = workbook.getWorksheet('Records')!
  expect(sheet.getCell('A1').value).toBe('SKU')
  expect(sheet.getCell('D2').value).toBe(5)
  expect(sheet.getCell('F2').value).toBe(1000)
  expect(sheet.views[0]).toMatchObject({ state: 'frozen', ySplit: 1 })
})

test('checkout rechecks stock and rejects invalid payment without changing records', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: 'Add Processor test part', exact: true }).click()
  await page.getByRole('button', { name: 'Review checkout' }).click()
  await page.getByLabel('Customer name', { exact: true }).fill('Buyer')
  await page.getByLabel('Amount received (PHP)', { exact: true }).fill('99999')
  await page.getByRole('button', { name: 'Complete sale' }).click()
  await expect(page.getByRole('alert')).toContainText('Payment exceeds')
  await page.getByLabel('Amount received (PHP)', { exact: true }).fill('0')
  await page.evaluate(() => {
    const key = 'jbc-rigworks:workspace:v1:admin@example.com'
    const data = JSON.parse(localStorage.getItem(key)!)
    data.inventory[0].stock = 0; localStorage.setItem(key, JSON.stringify(data))
  })
  await page.getByRole('button', { name: 'Complete sale' }).click()
  await expect(page.getByRole('alert')).toContainText('no longer has enough stock')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com')!).sales.length)).toBe(0)
})

test('new pages fit mobile screens, headings stick, and forms pass accessibility checks', async ({ page }) => {
  await setup(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const width of [320, 768, 1440]) {
    await page.setViewportSize({ width, height: 800 })
    for (const route of ['/pos', '/services', '/pc-building', '/pc-identifier', '/settings', '/reports']) {
      await page.goto(route)
      await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && Array.from(document.querySelectorAll('.page-content')).every(element => element.scrollWidth <= element.clientWidth))).toBe(true)
      await page.evaluate(() => document.querySelector('.page-content')!.scrollTo({ top: 700, behavior: 'instant' }))
      const header = await page.locator('.page-heading').boundingBox()
      expect(header!.y).toBeGreaterThanOrEqual(67)
      expect(header!.y).toBeLessThan(120)
    }
  }
  for (const route of ['/pos', '/services', '/pc-building', '/pc-identifier', '/settings']) {
    await page.goto(route)
    const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    expect(audit.violations.map(item => ({ id: item.id, targets: item.nodes.map(node => node.target) }))).toEqual([])
  }
})
