import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import QRCode from 'qrcode'
const inventory = ['Processor','Motherboard','Memory','Graphics','Storage','Power supply','Case','Cooling'].map((component,index) => ({ id:'stock-'+index,name:component+' sample',sku:'SKU-'+index,category:component,component,tier:'Mid',stock:4,minimum:1,price:1000,cost:500,specs:'Detailed specification '+index,socket:['Processor','Motherboard'].includes(component)?'AM5':'',memoryType:['Memory','Motherboard'].includes(component)?'DDR5':'' }))
async function setup(page:Page) { await page.goto('/login'); await page.evaluate(inventory=>{ localStorage.clear();sessionStorage.setItem('jbc-rigworks:session',JSON.stringify({id:'admin@test.com',email:'admin@test.com',name:'Admin',role:'admin'}));localStorage.setItem('jbc-rigworks:shop-owner:v1','admin@test.com');localStorage.setItem('jbc-rigworks:workspace:v1:admin@test.com',JSON.stringify({jobs:[],sales:[],expenses:[],inventory,bundles:[]})) },inventory);await page.goto('/dashboard') }
async function switchRole(page:Page,role:string) { await page.evaluate(role=>sessionStorage.setItem('jbc-rigworks:session',JSON.stringify({id:role+'@test.com',email:role+'@test.com',name:role,role})),role);await page.goto(role==='admin'?'/jobs':'/customer') }
test('directory CRUD feeds inventory and checkout fee presets',async({page})=>{
 await setup(page);await page.goto('/directories');await page.getByRole('button',{name:/CPU sockets/}).click();await page.getByLabel('New value',{exact:true}).fill('Custom socket');await page.getByRole('button',{name:'Add value',exact:true}).click();await page.getByRole('button',{name:'Edit Custom socket',exact:true}).click();await page.getByLabel('Edit value').fill('Test socket');await page.getByRole('button',{name:'Save value'}).click();await page.keyboard.press('Escape');await page.goto('/inventory');await page.getByRole('button',{name:'Add item'}).click();await expect(page.getByLabel('CPU / board socket').locator('option',{hasText:'Test socket'})).toHaveCount(1);await page.keyboard.press('Escape');await page.goto('/directories');await page.getByRole('button',{name:/VAT, fees & deductions/}).click();await page.getByRole('button',{name:'Add fee preset'}).click();await page.getByLabel('Preset name').fill('Packaging');await page.getByLabel('Amount or percentage').fill('25');await page.getByRole('button',{name:'Save fee preset'}).click();await page.keyboard.press('Escape');await page.goto('/pos');await page.getByRole('button',{name:'Add Processor sample',exact:true}).click();await page.getByRole('button',{name:'Review checkout'}).click();await page.getByText('Charges, discount & tax',{exact:true}).click();await page.getByLabel('Fee or deduction preset').selectOption({label:'Packaging / 25 PHP'});await expect(page.getByLabel('Other charges (PHP)',{exact:true})).toHaveValue('25');await expect(page.getByLabel('Other charge description')).toHaveValue('Packaging');await page.keyboard.press('Escape');await page.goto('/directories');await page.getByRole('button',{name:/CPU sockets/}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete Test socket',exact:true}).click();await expect(page.getByText('Test socket',{exact:true})).toHaveCount(0)
})
test('cash calculator applies payment, gives change and aligns POS columns',async({page})=>{
 await setup(page);await page.goto('/pos');const product=await page.locator('.pos-product').first().boundingBox(),order=await page.locator('.pos-layout>.panel').boundingBox();expect(Math.abs(product!.y-order!.y)).toBeLessThan(2);await page.getByRole('button',{name:'Add Processor sample',exact:true}).click();await page.getByRole('button',{name:'Review checkout'}).click();await page.getByLabel('Customer name',{exact:true}).fill('Cash buyer');await page.getByRole('button',{name:'Payment calculator'}).click();await page.getByLabel('Cash tendered (PHP)').fill('1500');await expect(page.getByRole('dialog',{name:'Payment calculator'})).toContainText('500.00');await page.getByRole('button',{name:'Apply payment'}).click();await expect(page.getByLabel('Amount received (PHP)',{exact:true})).toHaveValue('1000');await page.getByRole('button',{name:'Complete sale'}).click();await expect(page.getByRole('dialog')).toContainText('Change returned');const sale=await page.evaluate(()=>JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@test.com')!).sales[0]);expect(sale).toMatchObject({paid:1000,total:1000,cashTendered:1500,change:500})
})
test('QR photo and SKU lookup track stock, product specs, and deletion',async({page})=>{
 await setup(page);await page.goto('/inventory');await page.getByRole('button',{name:'Scan inventory QR'}).click();await page.getByLabel('QR code or SKU').fill('missing');await page.getByRole('button',{name:'Find inventory item'}).click();await expect(page.getByRole('alert')).toContainText('No item matches');const buffer=await QRCode.toBuffer('jbc-stock:stock-0');await page.getByLabel('Scan QR image').setInputFiles({name:'qr.png',mimeType:'image/png',buffer});await expect(page.locator('.qr-item')).toContainText('Processor sample');await expect(page.getByRole('link',{name:'Download QR label'})).toHaveAttribute('href',/^data:image/);await page.getByRole('button',{name:'Adjust scanned item'}).click();await page.getByLabel('Stock quantity',{exact:true}).fill('7');await page.getByLabel('Stock adjustment reason').fill('Delivery received');await page.getByLabel('Product photo',{exact:true}).setInputFiles({name:'product.png',mimeType:'image/png',buffer});await expect(page.locator('.upload-preview img')).toHaveAttribute('src',/^data:image/);await page.getByRole('button',{name:'Save changes'}).click();await expect(page.locator('.stock-history')).toContainText('Delivery received');await expect(page.locator('.stock-history')).toContainText('4 to 7');await page.keyboard.press('Escape');await page.getByRole('button',{name:'View Processor sample',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Detailed specification 0');await expect(page.locator('.product-photo img')).toHaveAttribute('src',/^data:image/);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Edit stock-0',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete record'}).click();await expect(page.getByRole('button',{name:'Edit stock-0',exact:true})).toHaveCount(0)
})
test('booking and online order requests can be processed by the workshop',async({page})=>{
 await setup(page);await switchRole(page,'customer');await page.goto('/customer/book');await page.getByRole('button',{name:'Start booking'}).click();await page.getByLabel('Device or model').fill('Customer PC');await page.getByLabel('Preferred date').fill('2027-01-15');await page.getByLabel('Preferred time').selectOption({index:1});await page.getByRole('button',{name:'Send request'}).click();await page.goto('/customer/shop');await page.getByRole('button',{name:'Add Processor sample',exact:true}).click();await page.getByRole('button',{name:'Review checkout'}).click();await page.getByRole('button',{name:'Place local order'}).click();await switchRole(page,'admin');await page.getByRole('button',{name:/^Review APT-/}).click();await page.getByRole('combobox',{name:'Request status',exact:true}).selectOption('Confirmed');await page.getByRole('button',{name:'Save request status'}).click();await page.getByRole('button',{name:/^Review APT-/}).click();await page.getByRole('button',{name:'Receive as service job'}).click();await expect(page.locator('.jobs-grid')).toContainText('Customer PC');await page.getByRole('button',{name:/^Review APT-/}).click();await expect(page.getByRole('button',{name:'Receive as service job'})).toBeDisabled();await page.keyboard.press('Escape');await page.getByRole('button',{name:/^Process INV-/}).click();await page.getByRole('combobox',{name:'Order status',exact:true}).selectOption('Ready');await page.getByRole('button',{name:'Save order status'}).click();await switchRole(page,'customer');await page.goto('/customer/records');await expect(page.getByRole('cell',{name:'Ready',exact:true})).toBeVisible();await page.goto('/customer/records?tab=appointments');await expect(page.getByText('Confirmed',{exact:true})).toBeVisible()
})
test('part tier filters, account dialogs and inventory modals fit small screens',async({page})=>{
 await setup(page);await page.emulateMedia({reducedMotion:'reduce'});for(const width of [320,768,1440]) {await page.setViewportSize({width,height:800});await page.goto('/pc-identifier');await expect(page.getByRole('heading',{name:'PC identifier',exact:true})).toBeVisible();await page.getByRole('button',{name:'Select Processor',exact:true}).click();await page.getByLabel('Spec tier filter').selectOption('High');await expect(page.getByLabel('Processor from stock').locator('option[value="stock-0"]')).toHaveCount(0);await page.getByLabel('Spec tier filter').selectOption('Mid');await expect(page.getByLabel('Processor from stock').locator('option[value="stock-0"]')).toHaveCount(1);expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Account and settings'}).click();await page.getByRole('button',{name:'Edit profile',exact:true}).click();await expect(page.getByLabel('Display name',{exact:true})).toBeVisible();expect(await page.getByRole('dialog',{name:'Account & contact'}).evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.goto('/inventory');await page.getByRole('button',{name:'Add item'}).click();expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(audit.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);await page.keyboard.press('Escape')}
})

test('bundle edits preserve stock references and deletion releases inventory',async({page})=>{
 await setup(page);await page.evaluate(()=>{const key='jbc-rigworks:workspace:v1:admin@test.com',data=JSON.parse(localStorage.getItem(key)!);data.bundles=[{id:'bundle-1',name:'Starter bundle',items:[{inventoryId:'stock-0',quantity:1},{inventoryId:'stock-2',quantity:1}]}];localStorage.setItem(key,JSON.stringify(data))});await page.goto('/inventory');await page.getByRole('button',{name:'Edit stock-0',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete record'}).click();await expect(page.getByRole('alert')).toContainText('Remove this item from its bundles');await page.keyboard.press('Escape');await page.goto('/pos');await page.getByRole('button',{name:'Bundles & PC sets',exact:true}).click();await page.getByRole('button',{name:'Edit bundle Starter bundle',exact:true}).click();await page.getByLabel('Bundle name').fill('Revised bundle');await page.getByLabel('Bundle quantity: Memory sample',{exact:true}).fill('2');await page.getByRole('button',{name:'Save bundle'}).click();await expect(page.getByRole('button',{name:'Choose Revised bundle',exact:true})).toBeVisible();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete bundle Revised bundle',exact:true}).click();await expect(page.getByRole('button',{name:'Choose Revised bundle',exact:true})).toHaveCount(0);const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@test.com')!));expect(data.bundles).toHaveLength(0);expect(data.inventory[0].stock).toBe(4)
})
test('pending customer requests edit and delete through detail dialogs',async({page})=>{
 await setup(page);await switchRole(page,'customer');await page.goto('/customer/book');await page.getByRole('button',{name:'Start booking'}).click();await page.getByLabel('Device or model').fill('Work laptop');await page.getByLabel('Preferred date').fill('2027-01-15');await page.getByLabel('Preferred time').selectOption({index:1});await page.getByRole('button',{name:'Send request'}).click();await page.goto('/customer/records?tab=appointments');await page.getByRole('button',{name:'View appointment details'}).click();await page.getByLabel('Request notes').fill('Bring replacement fan');await page.getByLabel('Preferred date').fill('2027-01-16');await page.getByRole('button',{name:'Save request changes'}).click();await expect(page.locator('.request-records')).toContainText('2027-01-16');await page.getByRole('button',{name:'View appointment details'}).click();await expect(page.getByLabel('Request notes')).toHaveValue('Bring replacement fan');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete request'}).click();await expect(page.getByRole('heading',{name:'No appointments yet'})).toBeVisible()
})
