import { test, expect, type Page } from '@playwright/test'
const stock = ['Processor', 'Motherboard', 'Memory', 'Graphics', 'Storage', 'Power supply', 'Case', 'Cooling'].map((component, index) => ({ id: 'p' + index, name: component + ' item', sku: 'P' + index, category: component, component, tier: 'Mid', stock: 10, minimum: 1, price: 1000, cost: 400, ...(index === 0 ? { warrantyMonths: '6', warrantyTerms: 'CPU warranty terms.' } : {}) }))
const settings = { name: 'Test shop', prefix: 'INV', taxRate: 10, labor: 0, homeSurcharge: '150', transportBase: '30', transportPerKm: '10', warrantyMonths: '12', warrantyTerms: 'Workshop parts warranty.', cleaning: { Desktop: { Low: '500', Mid: '700', High: '900' }, Laptop: { Low: '600', Mid: '800', High: '1000' } } }
async function setup(page: Page, role = 'admin') {
  await page.goto('/login')
  await page.evaluate(({ stock, settings, role }) => {
    localStorage.clear(); sessionStorage.clear()
    localStorage.setItem('jbc-rigworks:workspace:v1:admin@example.com', JSON.stringify({ jobs: [], sales: [], expenses: [], inventory: stock, bundles: [] }))
    localStorage.setItem('jbc-rigworks:shop-owner:v1', 'admin@example.com')
    localStorage.setItem('jbc-rigworks:shop-settings:v1', JSON.stringify(settings))
    sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: role + '@example.com', email: role + '@example.com', name: role, role }))
  }, { stock, settings, role })
  await page.goto(role === 'admin' ? '/pos' : '/customer/shop')
}
async function delivery(page: Page) {
  await page.getByRole('button', { name: 'Review checkout' }).click()
  await page.getByRole('combobox', { name: 'Fulfillment', exact: true }).selectOption('Delivery')
  await page.getByLabel('Delivery address').fill('123 Test street')
  await page.getByLabel('One-way road distance (km)').fill('5')
  await page.getByLabel('Customer contact', { exact: true }).fill('09123456789')
}
test('selected item bundles guarantee free delivery and preserve item warranty snapshots', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: 'Bundles & PC sets', exact: true }).click()
  await page.getByRole('button', { name: 'Create an item bundle', exact: true }).click()
  await page.getByLabel('Bundle name').fill('Upgrade bundle')
  await page.getByLabel('Processor', { exact: true }).selectOption('p0')
  await page.getByLabel('Memory', { exact: true }).selectOption('p2')
  await page.getByLabel('Bundle quantity: Processor item', { exact: true }).fill('1')
  await page.getByLabel('Bundle quantity: Memory item', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Save bundle' }).click()
  await expect(page.getByRole('button', { name: 'Choose Upgrade bundle', exact: true })).toBeVisible()
  await page.evaluate(() => sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: 'customer@example.com', email: 'customer@example.com', name: 'Customer', role: 'customer' })))
  await page.goto('/customer/shop')
  await expect(page.getByText('Create an item bundle')).toHaveCount(0)
  await page.getByRole('button', { name: 'Bundles & PC sets', exact: true }).click()
  await page.getByRole('button', { name: 'Choose Upgrade bundle', exact: true }).click()
  await delivery(page)
  await expect(page.locator('.fulfillment-note')).toContainText('free delivery guaranteed')
  await expect(page.locator('.checkout-totals > div').filter({ has: page.getByText('Delivery', { exact: true }) })).toContainText('0.00')
  await page.getByRole('button', { name: 'Place local order' }).click()
  await expect(page.getByRole('dialog')).toContainText('Free delivery guaranteed: Upgrade bundle')
  await expect(page.getByRole('dialog')).toContainText('Warranty: 6 months')
  await expect(page.getByRole('dialog')).toContainText('Warranty: 12 months')
  const sale = await page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com')!).sales[0])
  expect(sale.charges.delivery).toBe(0)
  expect(sale.total).toBe(3300)
  expect(sale.lines[0].warranty).toMatchObject({ months: 6, terms: 'CPU warranty terms.' })
  expect(sale.lines[0].warranty.expires).toMatch(/^\d{4}-\d{2}-\d{2}$/)
  await page.evaluate(() => localStorage.setItem('jbc-rigworks:shop-settings:v1', JSON.stringify({ warrantyMonths: '1', warrantyTerms: 'Changed terms' })))
  await page.goto('/customer/records')
  await page.getByRole('button', { name: /^Invoice INV-/ }).click()
  await expect(page.getByRole('dialog')).toContainText('Warranty: 12 months')
  await expect(page.getByRole('dialog')).not.toContainText('Changed terms')
})
test('single item delivery charges distance and complete PC sets deliver free', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: 'Add Processor item', exact: true }).click()
  await delivery(page)
  await page.getByLabel('Customer name', { exact: true }).fill('Walk-in buyer')
  await page.getByRole('button', { name: 'Complete sale' }).click()
  await expect(page.getByRole('dialog')).toContainText('5 km')
  const first = await page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com')!).sales[0])
  expect(first.charges.delivery).toBe(80)
  expect(first.total).toBe(1188)
  await page.goto('/pc-building')
  await page.getByRole('button', { name: /Everyday set/ }).click()
  await page.getByRole('button', { name: 'Order PC set' }).click()
  await delivery(page)
  await page.getByLabel('Customer name', { exact: true }).fill('Set buyer')
  await page.getByRole('button', { name: 'Complete sale' }).click()
  await expect(page.getByRole('dialog')).toContainText('Free delivery guaranteed: Complete PC set')
})
test('home service quotes and records contain separate surcharge and transport', async ({ page }) => {
  await setup(page, 'customer')
  await page.goto('/customer/book?device=Laptop&tier=Mid')
  await page.getByRole('button', { name: 'Start booking' }).click()
  await page.getByRole('combobox', { name: 'Visit type', exact: true }).selectOption('Home service')
  await page.getByLabel('Device or model').fill('My laptop')
  await page.getByLabel('Home-service address').fill('Test home address')
  await page.getByLabel('One-way road distance (km)').fill('5')
  await page.getByLabel('Preferred date').fill('2027-01-15')
  await page.getByRole('combobox', { name: 'Preferred time', exact: true }).selectOption('9:00 AM - 11:00 AM')
  await expect(page.locator('.checkout-totals')).toContainText('1,133.00')
  await page.getByRole('button', { name: 'Send request' }).click()
  await page.getByRole('button', { name: 'View my appointments' }).click()
  await page.getByRole('button', { name: 'View appointment details', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Test home address')
  const booking = await page.evaluate(() => JSON.parse(localStorage.getItem('jbc-rigworks:appointments:customer@example.com')!)[0])
  expect(booking.visit).toMatchObject({ mode: 'Home service', basePrice: 800, surcharge: 150, transport: 80, estimate: 1133 })
})
test('unset delivery rates require configuration and malformed records are not overwritten', async ({ page }) => {
  await setup(page)
  await page.evaluate(() => localStorage.setItem('jbc-rigworks:shop-settings:v1', '{}'))
  await page.reload()
  await page.getByRole('button', { name: 'Add Processor item', exact: true }).click()
  await delivery(page)
  await expect(page.getByRole('button', { name: 'Complete sale' })).toBeDisabled()
  await expect(page.getByRole('status')).toContainText('Delivery quote required')
  await page.evaluate(() => localStorage.setItem('jbc-rigworks:workspace:v1:admin@example.com', '{invalid'))
  await page.goto('/expenses')
  await expect(page.getByRole('alert')).toContainText('Saving is paused')
  await page.getByRole('button', { name: 'Record expense' }).click()
  await page.getByLabel('Description', { exact: true }).fill('Test')
  await page.getByLabel('Category', { exact: true }).fill('Test')
  await page.getByRole('button', { name: 'Save record' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Saving is paused')
  expect(await page.evaluate(() => localStorage.getItem('jbc-rigworks:workspace:v1:admin@example.com'))).toBe('{invalid')
})
test('headings remain stationary, dashboards are analytics-only, and customer navigation is simplified', async ({ page }) => {
  await setup(page)
  await page.goto('/dashboard')
  await expect(page.locator('.page-content').getByRole('link')).toHaveCount(0)
  await expect(page.locator('.page-content').getByRole('button')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Search workspace' })).toHaveCount(0)
  await expect(page.locator('.workspace-clock')).toContainText('Manila')
  for (const width of [320, 768, 1440]) {
    await page.setViewportSize({ width, height: 700 })
    await page.goto('/settings')
    const initial = await page.locator('.page-heading').boundingBox()
    const main = page.locator('.page-content')
    await main.evaluate(element => element.scrollTo({ top: 900, behavior: 'instant' }))
    expect(await main.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
    const scrolled = await page.locator('.page-heading').boundingBox()
    expect(scrolled!.y).toBe(initial!.y)
    expect((await page.locator('.topbar').boundingBox())!.y).toBe(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await main.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.evaluate(() => sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: 'customer@example.com', email: 'customer@example.com', name: 'Customer', role: 'customer' })))
  await page.goto('/customer')
  await expect(page.locator('.sidebar-nav a')).toHaveText(['Dashboard', 'Services & booking', 'PC builder', 'Shop', 'My records'])
  await page.goto('/inventory')
  await expect(page).toHaveURL(/customer$/)
})
