import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import ExcelJS from 'exceljs'
async function setup(page: Page, role = 'admin') {
  await page.goto('/login')
  await page.evaluate(role => {
    localStorage.clear(); sessionStorage.clear()
    const inventory = Array.from({ length: 27 }, (_, index) => ({ id: 'i' + index, name: 'Part ' + String(index + 1).padStart(2, '0'), sku: 'SKU-' + index, category: 'Storage', stock: index + 1, minimum: 2, price: (index + 1) * 100, cost: 50 }))
    localStorage.setItem('jbc-rigworks:workspace:v1:admin@example.com', JSON.stringify({ jobs: [], sales: [], expenses: [], inventory, bundles: [] }))
    localStorage.setItem('jbc-rigworks:shop-owner:v1', 'admin@example.com')
    sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: role + '@example.com', email: role + '@example.com', name: 'Test user', role }))
  }, role)
  await page.goto(role === 'admin' ? '/inventory' : '/customer')
}
test('Excel preview does not download until confirmed, and includes every numeric row', async ({ page }) => {
  await setup(page)
  let downloads = 0
  page.on('download', () => { downloads += 1 })
  await page.getByRole('button', { name: 'Export Excel' }).click()
  await expect(page.getByRole('dialog', { name: 'Excel preview' })).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('27 rows / 6 columns')
  await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(10)
  await page.getByRole('button', { name: 'Next page of Excel preview data' }).click()
  await expect(page.getByRole('dialog')).toContainText('Part 11')
  expect(downloads).toBe(0)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(downloads).toBe(0)
  await expect(page.getByRole('button', { name: 'Export Excel' })).toBeFocused()
  await page.getByRole('button', { name: 'Export Excel' }).click()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download Excel' }).click()
  const file = await pending
  const workbook = new ExcelJS.Workbook()
  await workbook.xlsx.readFile((await file.path())!)
  expect(workbook.worksheets[0].rowCount).toBe(28)
  expect(workbook.worksheets[0].getCell('F28').value).toBe(2700)
  expect(downloads).toBe(1)
})
test('tables paginate and sort numerically, reset the page on filtering, and sort on mobile', async ({ page }) => {
  await setup(page)
  await expect(page.locator('.data-table tbody tr')).toHaveCount(10)
  await page.getByRole('button', { name: 'Selling price', exact: true }).click()
  await page.getByRole('button', { name: 'Selling price', exact: true }).click()
  await expect(page.locator('.data-table tbody tr').first()).toContainText('Part 27')
  await page.getByRole('button', { name: 'Next page of Inventory', exact: true }).click()
  await expect(page.locator('.table-pagination')).toContainText('11-20 of 27')
  await page.getByLabel('Search inventory', { exact: true }).fill('Part 01')
  await expect(page.locator('.data-table tbody tr')).toHaveCount(1)
  await expect(page.locator('.data-table tbody tr')).toContainText('Part 01')
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 780 })
  await page.getByLabel('Sort Inventory', { exact: true }).selectOption({ label: 'Available' })
  await expect(page.locator('.data-table tbody tr').first()).toContainText('Part 01')
  await page.getByRole('button', { name: 'Reverse sort order' }).click()
  await expect(page.locator('.data-table tbody tr').first()).toContainText('Part 27')
  expect(await page.locator('.page-content').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})
test('profile changes can be cancelled or saved without changing business settings', async ({ page }) => {
  await setup(page)
  await page.goto('/settings')
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Display name', { exact: true }).fill('Discarded name')
  await page.keyboard.press('Escape')
  await expect(page.locator('.profile-card')).toContainText('Test user')
  await expect(page.getByRole('button', { name: 'Edit profile' })).toBeFocused()
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await expect(page.getByLabel('Display name', { exact: true })).toHaveValue('Test user')
  await page.getByLabel('Display name', { exact: true }).fill('Updated Owner')
  await page.getByLabel('Phone number').fill('09123456789')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.locator('.profile-card')).toContainText('Updated Owner')
  expect(await page.evaluate(() => localStorage.getItem('jbc-rigworks:shop-settings:v1'))).toBeNull()
})
test('checkout, booking, estimate, settings and Excel dialogs fit narrow screens and are accessible', async ({ page }) => {
  await setup(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const width of [320, 768, 1440]) {
    await page.setViewportSize({ width, height: 780 })
    for (const [route, action] of [['/inventory', 'Export Excel'], ['/settings', 'Edit profile'], ['/pos', 'Review checkout']]) {
      await page.goto(route)
      if (route === '/pos') await page.getByRole('button', { name: 'Add Part 01', exact: true }).click()
      await page.getByRole('button', { name: action, exact: true }).click()
      const dialog = page.getByRole('dialog')
      await expect(dialog).toBeVisible()
      expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
      const bounds = await dialog.boundingBox()
      expect(bounds!.x).toBeGreaterThanOrEqual(0)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
      if (width === 1440) {
        const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
        expect(audit.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) }))).toEqual([])
      }
      await page.keyboard.press('Escape')
    }
  }
  await page.evaluate(() => sessionStorage.setItem('jbc-rigworks:session', JSON.stringify({ id: 'customer@example.com', email: 'customer@example.com', name: 'Customer', role: 'customer' })))
  await page.goto('/customer/book')
  await page.setViewportSize({ width: 320, height: 740 })
  await page.getByRole('button', { name: 'Start booking' }).click()
  await page.getByRole('combobox', { name: 'Visit type', exact: true }).selectOption('Home service')
  expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  const estimate = page.locator('.estimate-card')
  expect(await estimate.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(await page.getByLabel('Device or model').evaluate(element => parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(16)
  const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(audit.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) }))).toEqual([])
})
