import { after, before, test } from 'node:test'
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { readFile } from 'node:fs/promises'
import { chromium, expect as baseExpect } from '@playwright/test'
import { initializeTestEnvironment } from '@firebase/rules-unit-testing'
import { collection, doc, getDocs, getDoc, updateDoc } from 'firebase/firestore'

if (!process.env.FIRESTORE_EMULATOR_HOST || !process.env.FIREBASE_AUTH_EMULATOR_HOST) throw new Error('Both local Firebase emulators are required.')
const projectId = 'demo-jbc-rigworks'
const expect = baseExpect.configure({ timeout: 15000 })
const origin = 'http://127.0.0.1:5179'
let env, browser, server
let serverOutput = ''
async function read(path) {
  let result
  await env.withSecurityRulesDisabled(async context => { result = (await getDoc(doc(context.firestore(), path))).data() })
  return result
}
async function list(path) {
  let result
  await env.withSecurityRulesDisabled(async context => { result = (await getDocs(collection(context.firestore(), path))).docs.map(doc => ({ ...doc.data(), id: doc.id })) })
  return result
}
const confirm = (page, title, label) => page.getByRole('dialog', { name: title, exact: true }).getByRole('button', { name: label, exact: true }).click()
async function register(page, name, email) {
  const verificationRequests = []
  const trackVerification = request => { if (request.url().includes('accounts:sendOobCode')) verificationRequests.push(request.url()) }
  page.on('request', trackVerification)
  await page.goto(`${origin}/register`)
  await page.getByLabel('Full name').fill(name)
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill('Test-password-123')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page).toHaveURL(/\/customer$/)
  const account = (await list('users')).find(user => user.email === email)
  assert.equal(account.role, 'user')
  await expect(page.getByRole('button', { name: 'Send verification email', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'I verified my email', exact: true })).toHaveCount(0)
  assert.deepEqual(verificationRequests, [])
  page.off('request', trackVerification)
  return account.id
}

async function verifyAdmin(page, id) {
  await expect(page.getByText(/Your account has been assigned an admin role/)).toBeVisible()
  await page.goto(`${origin}/dashboard`)
  await expect(page).toHaveURL(/\/customer$/)
  await page.getByRole('button', { name: 'Send verification email', exact: true }).click()
  await expect(page.getByText('Verification email sent.', { exact: true })).toBeVisible()
  const response = await fetch(`http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/projects/${projectId}/accounts:update`, {
    method: 'POST', headers: { Authorization: 'Bearer owner', 'Content-Type': 'application/json' },
    body: JSON.stringify({ localId: id, emailVerified: true }),
  })
  assert.equal(response.status, 200, await response.text())
  await page.getByRole('button', { name: 'I verified my email', exact: true }).click()
  await expect(page.getByRole('button', { name: 'I verified my email', exact: true })).toHaveCount(0)
}

before(async () => {
  env = await initializeTestEnvironment({ projectId, firestore: { rules: await readFile(new URL('../../firestore.rules', import.meta.url), 'utf8') } })
  await env.clearFirestore()
  await fetch(`http://127.0.0.1:9099/emulator/v1/projects/${projectId}/accounts`, { method: 'DELETE' })
  server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', '5179', '--strictPort'], {
    windowsHide: true,
    env: { ...process.env, VITE_FIREBASE_EMULATORS: 'true', VITE_FIREBASE_PROJECT_ID: projectId, VITE_FIREBASE_API_KEY: 'demo-key', VITE_FIREBASE_AUTH_DOMAIN: `${projectId}.firebaseapp.com`, VITE_FIREBASE_APP_ID: 'demo-app', VITE_FIREBASE_STORAGE_BUCKET: `${projectId}.appspot.com`, VITE_FIREBASE_MESSAGING_SENDER_ID: '123456' },
  })
  server.stdout.on('data', data => { serverOutput += data })
  server.stderr.on('data', data => { serverOutput += data })
  await expect.poll(async () => { try { return (await fetch(origin)).status } catch { return 0 } }, { timeout: 30000, message: 'Vite must start' }).toBe(200)
  browser = await chromium.launch({ channel: 'msedge', headless: true })
}, { timeout: 60000 })
after(async () => {
  await browser?.close()
  server?.kill()
  await env?.cleanup()
})

test('database workflows persist across customer/admin sessions', { timeout: 240000 }, async () => {
  const admin = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const buyer = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  admin.on('pageerror', error => errors.push(error.message))
  buyer.on('pageerror', error => errors.push(error.message))
  try {
    const adminId = await register(admin, 'Workshop owner', 'owner@example.test')
    await env.withSecurityRulesDisabled(context => updateDoc(doc(context.firestore(), 'users', adminId), { role: 'admin' }))
    await verifyAdmin(admin, adminId)
    await expect(admin).toHaveURL(/\/dashboard$/)
    await admin.goto(`${origin}/inventory`)
    await admin.getByRole('button', { name: 'Add item', exact: true }).click()
    const entry = admin.getByRole('dialog', { name: 'New inventory item' })
    for (const [name, value] of Object.entries({ name: 'Test processor', brand: 'Test', model: 'CPU', sku: 'CPU-001', category: 'Processor', stock: '3', minimum: '1', cost: '60', price: '100', specs: 'Six-core test processor' })) {
      await entry.locator(`[name="${name}"]`).fill(value)
    }
    await entry.locator('[name="component"]').selectOption('Processor')
    await entry.getByRole('button', { name: 'Save record', exact: true }).click()
    await confirm(admin, 'Save record?', 'Save record')
    await expect(entry).toHaveCount(0)
    const [item] = await list('inventory')
    assert.equal(item.stock, 3)
    assert.equal((await read(`catalog/${item.id}`)).cost, 0)

    await admin.goto(`${origin}/settings`)
    await admin.getByRole('button', { name: /Business & invoices/ }).click()
    await admin.getByLabel('Business name', { exact: true }).fill('Shared workshop')
    await admin.getByRole('button', { name: 'Save changes', exact: true }).click()
    await confirm(admin, 'Save changes?', 'Save changes')
    await expect(admin.getByRole('dialog', { name: 'Business & invoices', exact: true })).toHaveCount(0)
    assert.equal((await read('settings/shop')).name, 'Shared workshop')
    await admin.getByRole('button', { name: /Company payment QRs/ }).click()
    await expect(admin.getByText('No QR added', { exact: true })).toHaveCount(2)
    assert.deepEqual(await list('paymentAccounts'), [])
    await admin.getByRole('button', { name: 'Close Company payment QRs', exact: true }).click()

    const buyerId = await register(buyer, 'Customer', 'customer@example.test')
    await buyer.goto(`${origin}/customer/shop`)
    await buyer.getByRole('button', { name: 'Add Test CPU', exact: true }).click()
    await buyer.getByRole('button', { name: 'Review checkout', exact: true }).click()
    await expect(buyer.getByLabel('Fulfillment', { exact: true })).toHaveCount(0)
    await buyer.getByLabel('Receipt email', { exact: true }).fill('receipt@example.test')
    await buyer.getByRole('button', { name: 'Place order', exact: true }).click()
    await confirm(buyer, 'Place this order?', 'Place order')
    await expect(buyer.getByRole('dialog', { name: /^Order slip / })).toBeVisible()
    const [order] = await list('orders')
    assert.equal(order.customerId, buyerId)
    assert.equal(order.seller.name, 'Shared workshop')
    assert.equal((await read(`inventory/${item.id}`)).stock, 3)
    assert.equal((await list('sales')).length, 0)
    assert.equal((await list('receipts')).length, 0)
    assert.equal((await list('receiptEmails')).length, 0)
    assert.equal(order.fulfillment.mode, 'Pickup')
    assert.equal(order.paymentMethod, 'Cash')
    await expect(buyer.getByText('Payment: cash at the store. Bank and e-wallet QR payments are not available yet.', { exact: true })).toBeVisible()
    const qr = buyer.getByRole('dialog').getByRole('img', { name: `Order QR ${order.id}`, exact: true })
    await expect(qr).toBeVisible()
    const qrFile = { name: 'order-qr.png', mimeType: 'image/png', buffer: Buffer.from((await qr.getAttribute('src')).split(',')[1], 'base64') }

    await admin.goto(`${origin}/pos`)
    await admin.getByRole('button', { name: 'Scan order QR', exact: true }).click()
    await admin.getByLabel('Upload order QR', { exact: true }).setInputFiles(qrFile)
    await expect(admin.getByRole('dialog', { name: 'Scan customer order', exact: true })).toHaveCount(0)
    await expect(admin.getByRole('button', { name: 'Record payment', exact: true })).toBeDisabled()
    assert.equal((await read(`orders/${order.id}`)).paid, 0)
    await admin.getByRole('button', { name: 'Prepare order in POS', exact: true }).click()
    await confirm(admin, 'Prepare order in POS?', 'Prepare order')
    await expect(admin.getByRole('button', { name: 'Prepare order in POS', exact: true })).toHaveCount(0)
    assert.equal((await read(`inventory/${item.id}`)).stock, 2)
    assert.equal((await read(`catalog/${item.id}`)).stock, 2)
    assert.equal((await read(`sales/${order.id}`)).cost, 60)
    assert.equal((await read(`orders/${order.id}`)).cost, 0)
    await admin.getByLabel('Cash received (PHP)', { exact: true }).fill('40.10')
    await admin.getByRole('button', { name: 'Record payment', exact: true }).click()
    await confirm(admin, 'Record payment?', 'Record payment')
    await expect(admin.getByRole('dialog', { name: /^Receipt / })).toBeVisible()
    assert.equal((await read(`sales/${order.id}`)).status, 'Partial')
    assert.equal((await list('receipts')).length, 1)
    await admin.getByRole('button', { name: `Close Receipt ${order.id}`, exact: true }).click()
    await expect(admin.getByRole('button', { name: 'Confirm pickup', exact: true })).toHaveCount(0)
    await admin.getByLabel('Cash received (PHP)', { exact: true }).fill('100')
    await admin.getByRole('button', { name: 'Record payment', exact: true }).click()
    await confirm(admin, 'Record payment?', 'Record payment')
    await expect(admin.getByRole('dialog', { name: /^Receipt / })).toBeVisible()
    assert.equal((await read(`sales/${order.id}`)).paid, 100)
    assert.equal((await read(`orders/${order.id}`)).status, 'Paid')
    assert.equal((await read(`sales/${order.id}`)).change, 40.1)
    const receipts = await list('receipts'), emails = await list('receiptEmails')
    assert.equal(receipts.length, 2)
    assert.equal(emails.length, 2)
    assert.ok(receipts.every(receipt => receipt.sale.cost === 0 && receipt.sale.lines.every(line => line.unitCost === 0)))
    assert.ok(emails.every(email => email.status === 'Queued' && email.to === 'receipt@example.test' && email.message.text.includes(order.id)))
    await admin.getByRole('button', { name: `Close Receipt ${order.id}`, exact: true }).click()
    await admin.getByRole('button', { name: 'Scan order QR', exact: true }).click()
    await admin.getByLabel('Order QR or reference', { exact: true }).fill(`jbc-order:${order.id}`)
    await admin.getByRole('button', { name: 'Open order in POS', exact: true }).click()
    await expect(admin.getByRole('button', { name: 'Record payment', exact: true })).toBeDisabled()
    assert.equal((await list('receipts')).length, 2)
    assert.equal((await read(`inventory/${item.id}`)).stock, 2)
    await admin.getByRole('button', { name: 'Confirm pickup', exact: true }).click()
    await confirm(admin, 'Confirm pickup?', 'Confirm pickup')
    await expect(admin.getByText('Pickup completed.', { exact: true })).toBeVisible()
    await buyer.goto(`${origin}/customer/records?tab=orders`)
    await expect(buyer.getByRole('cell', { name: 'Paid', exact: true })).toBeVisible()
    await expect(buyer.getByRole('cell', { name: 'Completed', exact: true })).toBeVisible()
    await buyer.getByRole('button', { name: `Order QR and receipt ${order.id}`, exact: true }).click()
    await expect(buyer.getByRole('dialog', { name: /^Receipt / })).toBeVisible()
    await expect(buyer.getByText(/Receipt email prepared for receipt@example.test/)).toBeVisible()

    // Future manual transfers use explicitly configured company QRs, never a gateway.
    await admin.goto(`${origin}/settings`)
    await admin.getByRole('button', { name: /Company payment QRs/ }).click()
    const bank = admin.locator('.payment-account-card').filter({ has: admin.getByRole('heading', { name: 'Company bank QR', exact: true }) })
    await bank.getByLabel('Provider name', { exact: true }).fill('Test bank')
    await bank.getByLabel('Account holder', { exact: true }).fill('Test company')
    await bank.getByLabel('Account number or mobile number', { exact: true }).fill('TEST-001')
    await bank.getByLabel('Company QR image', { exact: true }).setInputFiles(qrFile)
    await expect(bank.getByRole('img', { name: 'Bank transfer company QR' })).toBeVisible()
    await bank.getByLabel('Offer this manual payment option').check()
    await bank.getByRole('button', { name: 'Save bank QR', exact: true }).click()
    await expect(bank.getByText('Payment account saved.', { exact: true })).toBeVisible()
    await buyer.goto(`${origin}/customer/shop`)
    await buyer.getByRole('button', { name: 'Add Test CPU', exact: true }).click()
    await buyer.getByRole('button', { name: 'Review checkout', exact: true }).click()
    await buyer.getByRole('button', { name: 'Place order', exact: true }).click()
    await confirm(buyer, 'Place this order?', 'Place order')
    await expect(buyer.getByRole('dialog', { name: /^Order slip / })).toBeVisible()
    const transferOrder = (await list('orders')).find(value => value.id !== order.id)
    await buyer.getByLabel('Manual payment option').selectOption('bank')
    await buyer.getByLabel('Transfer reference', { exact: true }).fill('TRANSFER-WRONG')
    await buyer.getByLabel('Payment proof image').setInputFiles(qrFile)
    await buyer.getByRole('button', { name: 'Submit proof for verification', exact: true }).click()
    await expect(buyer.getByRole('heading', { name: 'Payment proof awaiting review', exact: true })).toBeVisible()
    assert.equal((await read(`orders/${transferOrder.id}`)).paid, 0)
    assert.equal((await list('receipts')).length, 2)
    await admin.goto(`${origin}/jobs`)
    await admin.getByRole('tab', { name: 'Customer requests & online orders' }).click()
    await expect(admin.getByRole('cell', { name: 'Proof awaiting review', exact: true })).toBeVisible()
    await admin.getByRole('button', { name: `Open POS ${transferOrder.id}`, exact: true }).click()
    await admin.getByLabel('Reason for rejecting proof').fill('Reference does not match the company account')
    await admin.getByRole('button', { name: 'Reject proof', exact: true }).click()
    await confirm(admin, 'Reject payment proof?', 'Reject proof')
    await expect(buyer.getByText(/Previous proof rejected:/)).toBeVisible()
    await buyer.getByLabel('Transfer reference', { exact: true }).fill('TRANSFER-VERIFIED')
    await buyer.getByLabel('Payment proof image').setInputFiles(qrFile)
    await buyer.getByRole('button', { name: 'Submit proof for verification', exact: true }).click()
    await expect(admin.getByRole('heading', { name: 'Transfer proof awaiting verification' })).toBeVisible()
    await expect(admin.getByRole('button', { name: 'Record payment', exact: true })).toHaveCount(0)
    await admin.getByRole('button', { name: 'Prepare order in POS', exact: true }).click()
    await confirm(admin, 'Prepare order in POS?', 'Prepare order')
    await admin.getByRole('button', { name: 'Verify transfer and issue receipt', exact: true }).click()
    await confirm(admin, 'Record payment?', 'Record payment')
    await expect(admin.getByRole('dialog', { name: /^Receipt / })).toBeVisible()
    await expect(buyer.getByRole('dialog', { name: /^Receipt / })).toBeVisible()
    assert.equal((await read(`paymentProofs/${transferOrder.id}`)).status, 'Verified')
    assert.equal((await read(`orders/${transferOrder.id}`)).paid, 100)
    assert.equal((await read(`sales/${transferOrder.id}`)).paymentHistory[0].reference, 'TRANSFER-VERIFIED')
    assert.equal((await list('receipts')).length, 3)
    assert.equal((await list('receiptEmails')).length, 3)
    assert.equal((await read(`inventory/${item.id}`)).stock, 1)

    await buyer.goto(`${origin}/customer/book`)
    await buyer.getByRole('button', { name: 'Start booking', exact: true }).click()
    await buyer.getByLabel('Device or model').fill('Test laptop')
    const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10)
    await buyer.getByLabel('Preferred date').fill(tomorrow)
    await buyer.getByLabel('Preferred time').selectOption({ index: 1 })
    await buyer.getByRole('button', { name: 'Send request', exact: true }).click()
    await confirm(buyer, 'Send appointment request?', 'Send request')
    await expect(buyer.getByRole('heading', { name: 'Your appointment request is in.' })).toBeVisible()
    const [booking] = await list('appointments')
    assert.equal(booking.customerId, buyerId)
    await admin.goto(`${origin}/jobs`)
    await admin.getByRole('tab', { name: 'Customer requests & online orders' }).click()
    await admin.getByRole('button', { name: `Review ${booking.id}`, exact: true }).click()
    await admin.getByRole('button', { name: 'Receive as service job', exact: true }).click()
    await confirm(admin, 'Receive appointment?', 'Receive as job')
    await expect(admin.getByRole('dialog', { name: `Review ${booking.id}`, exact: true })).toHaveCount(0)
    assert.equal((await read(`appointments/${booking.id}`)).status, 'Confirmed')
    assert.equal((await read(`jobs/JOB-${booking.id}`)).device, 'Test laptop')
    await buyer.goto(`${origin}/customer/records?tab=appointments`)
    await expect(buyer.getByText('Confirmed', { exact: true })).toBeVisible()

    await buyer.goto(`${origin}/customer/settings`)
    await buyer.getByRole('button', { name: 'Edit profile', exact: true }).click()
    await buyer.getByLabel('Display name', { exact: true }).fill('Customer updated')
    await buyer.getByLabel('Phone number').fill('09123456789')
    await buyer.getByRole('button', { name: 'Save changes', exact: true }).click()
    await confirm(buyer, 'Save changes?', 'Save changes')
    await expect(buyer.getByRole('dialog', { name: 'Profile & contact', exact: true })).toHaveCount(0)
    await buyer.reload()
    await expect(buyer.locator('.profile-card')).toContainText('09123456789')
    assert.equal((await read(`users/${buyerId}/settings/account`)).phone, '09123456789')
    assert.equal((await read(`users/${buyerId}`)).name, 'Customer updated')
    await expect(buyer.getByRole('button', { name: 'Send verification email', exact: true })).toHaveCount(0)

    await buyer.goto(`${origin}/customer/pc-building?mode=identify`)
    await buyer.getByText('Add custom or owned parts', { exact: true }).click()
    await buyer.getByRole('button', { name: 'Edit Processor', exact: true }).click()
    await buyer.getByLabel('Processor from stock', { exact: true }).selectOption(item.id)
    await buyer.getByRole('button', { name: 'Use component', exact: true }).click()
    await buyer.getByRole('button', { name: 'Build details', exact: true }).click()
    await buyer.getByLabel('Build name', { exact: true }).fill('Saved customer build')
    await buyer.getByRole('dialog', { name: 'Build details', exact: true }).getByRole('button', { name: 'Save build', exact: true }).click()
    await confirm(buyer, 'Save this build?', 'Save build')
    await expect(buyer.getByRole('dialog', { name: 'Build details', exact: true })).toHaveCount(0)
    const [plan] = await list(`users/${buyerId}/plans`)
    assert.equal(plan.selection.Processor, item.id)
    await buyer.reload()
    await buyer.getByRole('button', { name: 'Build details', exact: true }).click()
    await buyer.getByLabel('Saved builds').selectOption(plan.id)
    await buyer.getByRole('button', { name: 'Close Build details', exact: true }).click()
    await buyer.getByRole('button', { name: 'Request a quote', exact: true }).click()
    await buyer.getByRole('button', { name: 'Send request', exact: true }).click()
    await confirm(buyer, 'Send build request?', 'Send request')
    await expect(buyer.getByRole('dialog', { name: 'Request this build', exact: true })).toHaveCount(0)
    const [pcRequest] = await list('pcRequests')
    assert.equal(pcRequest.parts[0].inventoryId, item.id)
    await admin.goto(`${origin}/jobs`)
    await admin.getByRole('tab', { name: 'Customer requests & online orders' }).click()
    await admin.getByRole('button', { name: `Review ${pcRequest.id}`, exact: true }).click()
    await admin.getByRole('button', { name: 'Prepare quote', exact: true }).click()
    await admin.getByLabel('Quoted total (PHP)').fill('120')
    await admin.getByLabel('Quote details').fill('Processor and assembly')
    await admin.getByRole('button', { name: 'Save quote', exact: true }).click()
    await confirm(admin, 'Save quote?', 'Save quote')
    await expect(admin.getByRole('dialog', { name: 'Prepare PC quote', exact: true })).toHaveCount(0)
    await buyer.goto(`${origin}/customer/records?tab=requests`)
    await buyer.getByRole('button', { name: 'View selected parts', exact: true }).click()
    await buyer.getByRole('button', { name: 'Accept quote', exact: true }).click()
    await confirm(buyer, 'Accept this quote?', 'Accept quote')
    await expect(buyer.getByRole('button', { name: 'Accept quote', exact: true })).toHaveCount(0)
    assert.equal((await read(`pcRequests/${pcRequest.id}`)).status, 'Approved')

    await env.withSecurityRulesDisabled(context => updateDoc(doc(context.firestore(), 'users', adminId), { role: 'user' }))
    await expect(admin).toHaveURL(/\/customer$/)
    assert.deepEqual(errors, [])
  } catch (error) {
    console.error('Admin URL:', admin.url(), 'Customer URL:', buyer.url())
    console.error('Visible errors:', await admin.locator('[role="alert"]').allTextContents(), await buyer.locator('[role="alert"]').allTextContents())
    console.error('Vite:', serverOutput.slice(-2000))
    throw error
  }
})
