import { useState, useSyncExternalStore } from 'react'
import { Link } from 'react-router-dom'
import { CalendarDays, Cpu, FileQuestion, Eye, Save, Trash2 } from 'lucide-react'
import { PageHeader } from '../../components/ui/PageHeader'
import { Panel } from '../../components/ui/Panel'
import { Dialog } from '../../components/ui/Dialog'
import { ActionButton } from '../../components/ui/ActionButton'
import { useAuth } from '../../lib/auth-context'
import { getAppointments, getPcRequests } from '../../lib/customerStorage'
import { formatPHP } from '../../data/appData'
import { today } from '../../lib/workspaceStorage'
import { useDirectories } from '../../lib/directories'
import type { CustomerAppointment, CustomPcRequest } from '../../types/business'
export function CustomerRecordsPage({ kind, embedded = false }: { kind: 'appointments' | 'requests'; embedded?: boolean }) {
 const { user } = useAuth(), [directory] = useDirectories()
 const [selected, setSelected] = useState<CustomerAppointment | CustomPcRequest | null>(null), [notes, setNotes] = useState(''), [date, setDate] = useState(''), [time, setTime] = useState(''), [error, setError] = useState('')
 const key = 'jbc-rigworks:' + (kind === 'appointments' ? 'appointments:' : 'pc-requests:') + user?.id
 useSyncExternalStore(callback => { window.addEventListener('storage',callback); window.addEventListener('jbc-requests-change',callback); return () => { window.removeEventListener('storage',callback); window.removeEventListener('jbc-requests-change',callback) } }, () => { try { return localStorage.getItem(key) } catch { return null } })
 if (!user) return null
 const appointments = getAppointments(user), requests = getPcRequests(user), isAppointments = kind === 'appointments'
 const rows = isAppointments ? appointments : requests
 function open(item: CustomerAppointment | CustomPcRequest) { setSelected(item);setNotes(item.notes);setDate('preferredDate' in item ? item.preferredDate : '');setTime('preferredTime' in item ? item.preferredTime : '');setError('') }
 function change(remove = false) { if (!selected) return; try { const current = JSON.parse(localStorage.getItem(key) || '[]') as (CustomerAppointment | CustomPcRequest)[]; if (!Array.isArray(current)) throw new Error('Saved requests could not be read.'); const latest=current.find(item=>item.id===selected.id); if (!latest || !['Requested','Under review'].includes(latest.status)) throw new Error('This request is being processed. Reopen it to see the current status.'); if (!remove && 'preferredDate' in latest && (!date || date < today() || !time)) throw new Error('Select a current or future date and a time.'); const next=remove?current.filter(item=>item.id!==selected.id):current.map(item=>item.id===selected.id?{...item,notes,...('preferredDate' in item?{preferredDate:date,preferredTime:time}:{})}:item);localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event('jbc-requests-change'));setSelected(null) } catch(err) {setError((err as Error).message || 'Unable to save your request.')} }
 const editable=selected&&['Requested','Under review'].includes(selected.status)
 return <>{!embedded&&<PageHeader eyebrow="CUSTOMER PORTAL" title={isAppointments?'My appointments':'My PC requests'} description="Your saved requests and their details."/>}<Panel title={isAppointments?'Appointment requests':'Custom build requests'}>{!rows.length?<div className="customer-empty large"><FileQuestion size={30}/><h3>{isAppointments?'No appointments yet':'No PC requests yet'}</h3><Link className="primary-button" to={isAppointments?'/customer/book':'/customer/pc-building'}>{isAppointments?<CalendarDays size={16}/>:<Cpu size={16}/>} {isAppointments?'Book a service':'Start a PC request'}</Link></div>:<div className="request-records">{rows.map(item=><article key={item.id}><div className="request-record-heading"><div><strong>{'service' in item?item.service:item.useCase+' PC'}</strong><small>{item.id}{'device' in item?' / '+item.device:''}</small></div><em>{item.status}</em></div><p>{'preferredDate' in item?item.preferredDate+' / '+item.preferredTime:item.tier || 'Tier to be confirmed'}</p><ActionButton label={'service' in item?'View appointment details':'View selected parts'} onClick={()=>open(item)}><Eye size={20}/></ActionButton></article>)}</div>}</Panel>
 {selected&&<Dialog title={'service' in selected?'Appointment details':'Build request details'} onClose={()=>setSelected(null)}><div className="portal-form settings-fields">{'service' in selected?<><h3>{selected.service} / {selected.device}</h3>{selected.visit&&<><p>{selected.visit.mode} / {selected.visit.address} {selected.visit.mode==='Home service'?selected.visit.distanceKm+' km one way':''}</p><dl className="checkout-totals">{[['Service',selected.visit.basePrice],['Home surcharge',selected.visit.surcharge],['Transportation',selected.visit.transport],['Estimated total',selected.visit.estimate]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value===null?'Quote required':formatPHP(Number(value))}</dd></div>)}</dl></>}<label>Preferred date<input type="date" required min={today()} disabled={!editable} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Preferred time<select disabled={!editable} value={time} onChange={e=>setTime(e.target.value)}>{[...new Set([time,...directory.times])].filter(Boolean).map(value=><option key={value}>{value}</option>)}</select></label></>:<><p>{selected.useCase} / Budget {selected.budget || 'Not specified'}</p>{selected.parts?.map(part=><p key={part.component}><strong>{part.component}:</strong> {part.model} ({part.source})</p>)}</>}<label>Request notes<textarea rows={4} maxLength={1000} value={notes} disabled={!editable} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}{editable&&<div className="dialog-actions"><ActionButton label="Delete request" onClick={()=>{if(window.confirm('Delete this pending request?'))change(true)}}><Trash2 size={20}/></ActionButton><ActionButton label="Save request changes" onClick={()=>change()}><Save size={20}/></ActionButton></div>}</div></Dialog>}</>
}
