import { useState, type FormEvent } from 'react'
import { Boxes, Plus, Pencil, Save, Trash2, ShoppingCart } from 'lucide-react'
import { Dialog } from '../../components/ui/Dialog'
import { ActionButton } from '../../components/ui/ActionButton'
import { useWorkspace } from '../../lib/workspaceStorage'
import { useAuth } from '../../lib/auth-context'
import { components, componentOf, compatibility, isPcPart, isSellable } from '../../lib/pc'
import { formatPHP } from '../../data/appData'
import type { ProductBundle } from '../../types/business'
import { useConfirmation } from '../../components/ui/confirmation-context'
export function BundleCatalog({ onSelect }: { onSelect: (bundle: ProductBundle) => void }) {
 const workspace = useWorkspace(), { user } = useAuth()
 const { confirm } = useConfirmation()
 const [draft, setDraft] = useState<ProductBundle | null>(null), [error, setError] = useState('')
 const [kind, setKind] = useState('PC set')
 async function save(event: FormEvent) { event.preventDefault(); if (!draft) return; setError(''); try {
   if (!draft.name.trim() || draft.items.length < 2 || draft.items.some(part => !Number.isSafeInteger(part.quantity) || part.quantity < 1 || !workspace.inventory.some(item => item.id === part.inventoryId && isSellable(item) && (kind !== 'PC set' || isPcPart(item)) && item.stock >= part.quantity))) throw new Error('Name the bundle and select at least two different available items with valid quantities.')
   const conflicts = compatibility(workspace.inventory.filter(item => draft.items.some(part => part.inventoryId === item.id)))
   if (conflicts.length) throw new Error(conflicts.join(' '))
   if (!await confirm({ title: 'Save bundle?', message: `Save ${draft.name.trim()} with its selected inventory items?`, confirmLabel: 'Save bundle' })) return
   workspace.save('bundles', { ...draft, name: draft.name.trim() }); setDraft(null)
 } catch (err) { setError((err as Error).message) } }
 function choose(component: string, id: string) { if (!draft) return; setDraft({ ...draft, items: [...draft.items.filter(part => componentOf(workspace.inventory.find(item => item.id === part.inventoryId)!) !== component), ...(id ? [{ inventoryId: id, quantity: 1 }] : [])] }) }
 return <section className="bundle-catalog" aria-label="Item bundles"><div className="section-toolbar"><h2><Boxes size={22}/> Bundles & PC sets</h2>{user?.role === 'admin' && <ActionButton variant="labeled" label="Create bundle" onClick={() => { setDraft({ id: crypto.randomUUID(), name: '', items: [] }); setKind('PC set'); setError('') }}><Plus size={18}/></ActionButton>}</div>
 <div className="pos-products">{workspace.bundles.map(bundle => { const available = bundle.items.every(part => workspace.inventory.some(item => item.id === part.inventoryId && isSellable(item) && item.stock >= part.quantity)); const total = bundle.items.reduce((sum, part) => sum + (workspace.inventory.find(item => item.id === part.inventoryId)?.price || 0) * part.quantity, 0); return <article className="pos-product" key={bundle.id}><Boxes size={30}/><h3>{bundle.name}</h3><ul className="bundle-part-list">{bundle.items.map(part => <li key={part.inventoryId}>{part.quantity} x {workspace.inventory.find(item => item.id === part.inventoryId)?.name || 'Unavailable item'}</li>)}</ul><strong>{formatPHP(total)}</strong><span className="save-message">Free delivery included</span><div className="part-actions"><ActionButton variant="labeled" label="Choose bundle" disabled={!available} onClick={() => onSelect(bundle)}><ShoppingCart size={18}/></ActionButton>{user?.role === 'admin' && <><ActionButton label={'Edit bundle ' + bundle.name} onClick={() => { setDraft(structuredClone(bundle)); setKind('Item bundle'); setError('') }}><Pencil size={18}/></ActionButton><ActionButton label={'Delete bundle ' + bundle.name} onClick={async () => { if (!await confirm({ title: 'Delete bundle?', message: `Delete ${bundle.name}? Existing orders will keep their saved details.`, confirmLabel: 'Delete bundle', tone: 'danger' })) return; try { workspace.remove('bundles', bundle.id) } catch (err) { setError((err as Error).message) } }}><Trash2 size={18}/></ActionButton></>}{!available && <small>Out of stock</small>}</div></article> })}</div>
 {!workspace.bundles.length && <p className="storage-caption">No bundles listed yet.</p>}{error && !draft && <p role="alert" className="form-error">{error}</p>}
 {draft && <Dialog title="Bundle editor" wide onClose={() => setDraft(null)}><form className="portal-form settings-fields" onSubmit={save}><div className="portal-form-grid"><label>Bundle name<input required maxLength={100} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></label><label>Selection mode<select value={kind} onChange={e => setKind(e.target.value)}><option>PC set</option><option>Item bundle</option></select></label></div>
 {kind === 'PC set' ? <div className="portal-form-grid">{components.map(component => <label key={component.name}>{component.name}<select aria-label={component.name} value={draft.items.find(part => componentOf(workspace.inventory.find(item => item.id === part.inventoryId)!) === component.name)?.inventoryId || ''} onChange={e => choose(component.name,e.target.value)}><option value="">Select available stock</option>{workspace.inventory.filter(item => isPcPart(item) && item.stock > 0 && componentOf(item) === component.name).map(item => <option key={item.id} value={item.id}>{item.name} / {item.tier || 'Unrated'} / {item.stock} in stock</option>)}</select></label>)}</div> : <><label>Add stock item<select value="" onChange={e => { if (e.target.value) setDraft({ ...draft, items: [...draft.items, { inventoryId: e.target.value, quantity: 1 }] }) }}><option value="">Choose available inventory</option>{workspace.inventory.filter(item => isSellable(item) && item.stock > 0 && !draft.items.some(part => part.inventoryId === item.id)).map(item => <option key={item.id} value={item.id}>{item.name} / {item.stock} in stock</option>)}</select></label></>}
 <div className="bundle-items">{draft.items.map(part => { const item = workspace.inventory.find(item => item.id === part.inventoryId); return <div className="directory-row" key={part.inventoryId}><label>{item?.name || 'Unavailable item'}<input aria-label={'Bundle quantity: ' + item?.name} type="number" min="1" max={item?.stock || 0} step="1" value={part.quantity} onChange={e => setDraft({ ...draft, items: draft.items.map(value => value.inventoryId === part.inventoryId ? { ...value, quantity: Number(e.target.value) } : value) })}/></label><ActionButton label={'Remove bundle item ' + item?.name} onClick={() => setDraft({ ...draft, items: draft.items.filter(value => value.inventoryId !== part.inventoryId) })}><Trash2 size={18}/></ActionButton></div> })}</div>{error && <p role="alert" className="form-error">{error}</p>}<div className="dialog-actions"><ActionButton type="submit" variant="labeled" label="Save bundle"><Save size={18}/></ActionButton></div></form></Dialog>}</section>
}
