import { useState } from 'react'
import { Check, RotateCcw, Delete } from 'lucide-react'
import { Dialog } from '../../components/ui/Dialog'
import { formatPHP } from '../../data/appData'
export function PaymentCalculator({ total, onApply, onClose }: { total: number; onApply: (paid: number, tender: number) => void; onClose: () => void }) {
 const [amount, setAmount] = useState(''), [error, setError] = useState('')
 const tender = Number(amount), valid = amount !== '' && Number.isFinite(tender) && tender >= 0 && tender <= 1e12
 function key(value: string) { if (value === '.' && amount.includes('.')) return; setAmount(current => current.length < 16 ? current + value : current); setError('') }
 return <Dialog title="Payment calculator" onClose={onClose}><div className="payment-calculator portal-form"><dl className="checkout-totals"><div><dt>Invoice total</dt><dd>{formatPHP(total)}</dd></div><div><dt>Change to return</dt><dd>{formatPHP(valid ? Math.max(0, tender-total) : 0)}</dd></div><div><dt>Remaining balance</dt><dd>{formatPHP(valid ? Math.max(0,total-tender) : total)}</dd></div></dl><label>Cash tendered (PHP)<input inputMode="decimal" type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)}/></label><div className="calculator-keys">{['7','8','9','4','5','6','1','2','3','.','0','00'].map(value => <button type="button" className="secondary-button" key={value} onClick={() => key(value)}>{value}</button>)}<button type="button" className="secondary-button" title="Clear" aria-label="Clear" onClick={() => setAmount('')}><RotateCcw size={18}/></button><button type="button" className="secondary-button" title="Backspace" aria-label="Backspace" onClick={() => setAmount(amount.slice(0,-1))}><Delete size={18}/></button><button type="button" className="primary-button" title="Apply payment" aria-label="Apply payment" onClick={() => { if (!valid) { setError('Enter a valid cash amount.'); return } onApply(Math.round(Math.min(tender,total)*100)/100, Math.round(tender*100)/100); onClose() }}><Check size={20}/></button></div><div className="quick-cash">{[100,500,1000].map(value => <button className="secondary-button" key={value} onClick={() => setAmount(String(Math.round((Number(amount || 0)+value)*100)/100))}>+{value}</button>)}</div>{error && <p className="form-error" role="alert">{error}</p>}</div></Dialog>
}
