import { useState, useSyncExternalStore } from 'react'
import { ClipboardList, Eye, Save, Wrench, ReceiptText } from 'lucide-react'
import { Dialog } from '../../components/ui/Dialog'
import { ActionButton } from '../../components/ui/ActionButton'
import { DataTable } from '../../components/ui/DataTable'
import { Panel } from '../../components/ui/Panel'
import { useAuth } from '../../lib/auth-context'
import { useWorkspace } from '../../lib/workspaceStorage'
import { InvoiceDialog } from '../sales/InvoiceDialog'
import type { CustomerAppointment, CustomPcRequest, Sale } from '../../types/business'
type RequestRow = { id: string; key: string; owner: string; kind: 'Booking' | 'PC request'; record: CustomerAppointment | CustomPcRequest }
function snapshot() { try { return JSON.stringify(Object.keys(localStorage).filter(key => key.startsWith('jbc-rigworks:appointments:') || key.startsWith('jbc-rigworks:pc-requests:')).sort().map(key => [key, localStorage.getItem(key)])) } catch { return '[]' } }
function subscribe(fn: () => void) { window.addEventListener('storage',fn); window.addEventListener('jbc-requests-change',fn); return () => { window.removeEventListener('storage',fn); window.removeEventListener('jbc-requests-change',fn) } }
export function RequestInbox() {
 const raw = useSyncExternalStore(subscribe,snapshot), { user } = useAuth(), workspace = useWorkspace()
 const [selected, setSelected] = useState<RequestRow | null>(null), [status, setStatus] = useState(''), [error, setError] = useState(''), [invoice, setInvoice] = useState<Sale | null>(null), [order, setOrder] = useState<Sale | null>(null), [orderStatus, setOrderStatus] = useState('Requested')
 const rows: RequestRow[] = []; let invalid = false
 for (const [key,value] of JSON.parse(raw) as [string,string][]) { try { const data = JSON.parse(value); if (!Array.isArray(data)) throw new Error(); for (const record of data) { if (!record || typeof record.id !== 'string' || typeof record.status !== 'string') { invalid = true; continue } if (record.shopId && record.shopId !== user?.id) continue; rows.push({ id: record.id, key, owner: record.customerName || key.split(':').slice(2).join(':'), kind: key.includes(':appointments:') ? 'Booking' : 'PC request', record }) } } catch { invalid = true } }
 function updateRequest(nextStatus = status) { if (!selected) return; try { const current = JSON.parse(localStorage.getItem(selected.key) || '[]'); if (!Array.isArray(current) || !current.some(record => record.id === selected.id)) throw new Error('This request is no longer available.'); localStorage.setItem(selected.key,JSON.stringify(current.map(record => record.id === selected.id ? { ...record, status: nextStatus } : record))); window.dispatchEvent(new Event('jbc-requests-change')); setSelected(null); setError('') } catch (err) { setError((err as Error).message || 'Could not update the request.') } }
 function receive() { if (!selected || !('service' in selected.record)) return; try { const record = selected.record; const id = 'JOB-' + record.id; if (workspace.jobs.some(job => job.id === id)) throw new Error('This request already has a service job.'); workspace.save('jobs',{ id,customer:selected.owner,device:record.device,service:record.service + (record.visit?.mode === 'Home service' ? ' / Home service: ' + record.visit.address : ''),due:record.preferredDate,quote:record.visit?.estimate || 0,status:'Queued' }); setError(''); updateRequest('Confirmed') } catch (err) { setError((err as Error).message) } }
 const orders = workspace.sales.filter(sale => sale.channel === 'Online')
 return <div className="request-inbox"><Panel title="Customer requests" subtitle="Bookings and PC requests saved in this browser" action={<ClipboardList size={22}/>}><DataTable rows={rows} label="Customer requests" columns={[{label:'Customer',sortValue:row=>row.owner,render:row=>row.owner},{label:'Type',render:row=>row.kind},{label:'Request',render:row=>'service' in row.record ? row.record.service : row.record.notes},{label:'Status',render:row=>row.record.status},{label:'Actions',render:row=><ActionButton label={'Review ' + row.id} onClick={()=>{setSelected(row);setStatus(row.record.status);setError('')}}><Eye size={18}/></ActionButton>}]}/></Panel>
 <Panel title="Online transactions" subtitle="Process pickup and delivery orders"><DataTable rows={orders} label="Online transactions" columns={[{label:'Customer',render:row=>row.customer},{label:'Invoice',render:row=>row.id},{label:'Fulfillment',render:row=>row.fulfillment?.mode || 'Pickup'},{label:'Status',render:row=>row.orderStatus || 'Requested'},{label:'Actions',render:row=><div className="part-actions"><ActionButton label={'Process ' + row.id} onClick={()=>{setOrder(row);setOrderStatus(row.orderStatus || 'Requested');setError('')}}><Wrench size={18}/></ActionButton><ActionButton label={'Invoice ' + row.id} onClick={()=>setInvoice(row)}><ReceiptText size={18}/></ActionButton></div>}]}/></Panel>{invalid && <p role="alert" className="form-error">Some saved requests could not be read. Their original data has been preserved.</p>}
 {selected && <Dialog title={'Review ' + selected.id} onClose={()=>setSelected(null)}><div className="portal-form settings-fields"><h3>{selected.owner}</h3><p>{selected.record.customerEmail}</p>{'service' in selected.record ? <dl className="detail-list"><div><dt>Service</dt><dd>{selected.record.service}</dd></div><div><dt>Device</dt><dd>{selected.record.device}</dd></div><div><dt>Schedule</dt><dd>{selected.record.preferredDate} / {selected.record.preferredTime}</dd></div><div><dt>Visit</dt><dd>{selected.record.visit?.mode || 'Workshop'} {selected.record.visit?.address}</dd></div></dl> : <><p>{selected.record.useCase} / {selected.record.tier || 'Unclassified'}</p><ul>{selected.record.parts?.map(part=><li key={part.component}>{part.component}: {part.model}</li>)}</ul><p>Budget: {selected.record.budget || 'Not specified'}</p></>}<p className="product-specs">{selected.record.notes}</p><label>Request status<select aria-label="Request status" value={status} onChange={e=>setStatus(e.target.value)}>{(selected.kind==='Booking' ? ['Requested','Confirmed','Completed','Cancelled'] : ['Under review','Quoted','Approved']).map(value=><option key={value}>{value}</option>)}</select></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="dialog-actions">{selected.kind==='Booking'&&<ActionButton label="Receive as service job" disabled={workspace.jobs.some(job=>job.id==='JOB-'+selected.id)} onClick={receive}><Wrench size={20}/></ActionButton>}<ActionButton label="Save request status" onClick={() => updateRequest()}><Save size={20}/></ActionButton></div></div></Dialog>}
 {order && <Dialog title={'Process ' + order.id} onClose={()=>setOrder(null)}><div className="portal-form settings-fields"><p>{order.customer} / {order.contact}</p><p>{order.detail}</p><p>{order.fulfillment?.address}</p><label>Order status<select aria-label="Order status" value={orderStatus} onChange={e=>setOrderStatus(e.target.value)}>{['Requested','Processing','Ready','Completed'].map(value=><option key={value}>{value}</option>)}</select></label>{error&&<p role="alert" className="form-error">{error}</p>}<ActionButton label="Save order status" onClick={()=>{try { const latest=workspace.sales.find(value=>value.id===order.id); if(!latest) throw new Error('Order unavailable.'); workspace.save('sales',{...latest,orderStatus:orderStatus as Sale['orderStatus']});setOrder(null) } catch(err){setError((err as Error).message)}}}><Save size={20}/></ActionButton></div></Dialog>}{invoice&&<InvoiceDialog sale={invoice} onClose={()=>setInvoice(null)}/>}</div>
}
