'use client';
import {useState,useEffect,useMemo,useCallback,useRef,type ReactNode,type CSSProperties} from 'react';
import {LayoutDashboard,Wrench,ShoppingBag,Package,ReceiptText,ChartNoAxesCombined,Plus,ArrowUpRight,ArrowRight,Wallet,TrendingUp,Coins,Download,Search,RefreshCw,LockKeyhole,ChevronRight,TriangleAlert,Check,FlaskConical,SlidersHorizontal,Undo2} from 'lucide-react';
import {AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarProvider,SidebarTrigger,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogHeader,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Skeleton} from '@/components/ui/skeleton';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {RecordForm,Choice,type Modal} from './hub-forms';
import {emptyWorkspace,demoWorkspace,newId,money,today,dateLabel,monthLabel,paymentStatus,summary,unitCost,jobStatuses,type Workspace,type Sale} from '@/lib/business';

const nav=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'jobs',label:'Service jobs',icon:Wrench},{id:'sales',label:'Sales & payments',icon:ShoppingBag},{id:'inventory',label:'Inventory',icon:Package},{id:'expenses',label:'Expenses',icon:ReceiptText},{id:'reports',label:'Reports',icon:ChartNoAxesCombined}] as const;
type View=typeof nav[number]['id'];
const pageCopy:Record<View,{title:string;description:string}>={overview:{title:'Business overview',description:'A clear picture of your workshop, numbers, and next steps.'},jobs:{title:'Service jobs',description:'Keep every repair, clean, and build moving.'},sales:{title:'Sales & payments',description:'Every sale, every payment, every outstanding balance.'},inventory:{title:'Inventory',description:'Know what is on hand and what needs restocking.'},expenses:{title:'Expenses',description:'Keep track of the costs of running your business.'},reports:{title:'Business reports',description:'See what you earned, spent, and collected.'}};

function Badge({children}:{children:ReactNode}){const s=String(children);return <span className={'status '+(['Paid','Completed','In stock'].includes(s)?'green':['Unpaid','Low stock','Queued'].includes(s)?'amber':['In progress','Partial','Ready'].includes(s)?'blue':['Voided','Cancelled','Out of stock'].includes(s)?'gray':'gray')}>{children}</span>;}
function Blank({title,description,icon:Icon=Package,action}:{title:string;description:string;icon?:typeof Package;action?:ReactNode}){return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><Icon/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{action}</Empty>;}
function Metric({title,value,note,icon:Icon,dark=false}:{title:string;value:string;note:string;icon:typeof Package;dark?:boolean}){return <article className={'metric '+(dark?'metric-dark':'')}><div className="metric-top"><span>{title}</span><Icon size={18}/></div><strong>{value}</strong><p>{note}</p></article>;}
function Panel({title,subtitle,action,children,className=''}:{title:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}><div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>;}
function csvDownload(name:string,rows:(string|number)[][]){
 const cell=(v:string|number)=>{let t=String(v);if(typeof v==='string'&&/^[=+@\-\t\r]/.test(t))t="'"+t;return '"'+t.replaceAll('"','""')+'"';};
 const content='\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n');
 const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}

export default function BusinessHub(){return <SidebarProvider style={{'--sidebar-width':'15.5rem'} as CSSProperties}><Hub/><Toaster theme="light" position="bottom-right" richColors/></SidebarProvider>;}

function Hub(){
 const [view,setView]=useState<View>('overview'),[data,setData]=useState<Workspace>(emptyWorkspace),[demo,setDemo]=useState(false),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
 const [period,setPeriod]=useState(today().slice(0,7)),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[modal,setModal]=useState<Modal|null>(null),[confirm,setConfirm]=useState<{action:string;id:string;title:string;description:string}|null>(null),[busy,setBusy]=useState(false);
 const {setOpenMobile}=useSidebar();
 const samples=useMemo(demoWorkspace,[]),w=demo?samples:data,s=useMemo(()=>summary(w,period),[w,period]);
 const stateRef=useRef({w,period,demo,view});stateRef.current={w,period,demo,view};
 const refresh=useCallback(async()=>{setLoadError('');try{const r=await fetch('/api/workspace',{cache:'no-store'});const d=await r.json() as Workspace&{error?:string};if(!r.ok)throw new Error(d.error||'Unable to load the workspace.');setData(d);return true;}catch(e){setLoadError(e instanceof Error?e.message:'Unable to load the workspace.');return false;}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 const navigate=useCallback((v:View)=>{setView(v);setSearch('');setFilter('all');setOpenMobile(false);},[setOpenMobile]);
 useEffect(()=>{
  type Context={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},opts:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:Parameters<Context['registerTool']>[0])=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'read_business_summary',title:'Read business summary',description:'Read current displayed JBC sales, costs, profit, and outstanding balances. Identifies sample data when shown.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');const {w,period,demo}=stateRef.current;const {sales,...totals}=summary(w,period);return {currency:'PHP',amountUnit:'centavos',period,sampleData:demo,saleCount:sales.length,...totals};}});
  register({name:'navigate_business_view',title:'Open business view',description:'Navigate to a JBC business view. Does not create or change any business records.',inputSchema:{type:'object',properties:{view:{type:'string',enum:nav.map(n=>n.id)}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const value=input as {view:string};if(!value||Object.keys(value).length!==1||!nav.some(n=>n.id===value.view))throw new Error('Choose a valid business view.');navigate(value.view as View);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {view:value.view};}});
  return ()=>lifecycle.abort();
 },[navigate]);
 async function save(payload:Record<string,unknown>,requestId:string){
  if(demo)throw new Error('Open your real workspace to save records.');
  const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestId})});
  const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not save the entry.');
  const refreshed=await refresh();if(refreshed)toast.success('Saved to your workspace');else toast.info('Saved. Refresh to see the latest figures.');
 }
 const months=useMemo(()=>{
  const values=new Set([today().slice(0,7),...w.sales.map(x=>x.date.slice(0,7)),...w.expenses.map(x=>x.date.slice(0,7)),...w.payments.map(x=>x.date.slice(0,7)),...w.movements.map(x=>x.date.slice(0,7))]);
  const dt=new Date(today()+'T00:00:00');for(let n=0;n<12;n++){values.add(dt.getFullYear()+'-'+String(dt.getMonth()+1).padStart(2,'0'));dt.setDate(1);dt.setMonth(dt.getMonth()-1);}return [...values].sort().reverse();
 },[w]);
 const activeJobs=w.jobs.filter(j=>!['Completed','Cancelled'].includes(j.status));
 const lowStock=w.items.filter(i=>i.stock<=i.minimum);
 const found=(...values:unknown[])=>values.join(' ').toLowerCase().includes(search.toLowerCase());
 const inPeriod=(date:string)=>period==='all'||date.startsWith(period);
 const sales=w.sales.filter(x=>inPeriod(x.date)&&found(x.code,x.customer,...x.lines.map(l=>l.description))&&(filter==='all'||(filter==='unpaid'?x.status==='active'&&x.paid<x.total:filter==='paid'?paymentStatus(x)==='Paid':x.status==='void')));
 const items=w.items.filter(x=>found(x.name,x.sku,x.category)&&(filter!=='low'||x.stock<=x.minimum));
 const jobs=w.jobs.filter(x=>found(x.customer,x.device,x.service)&&(filter==='all'||(filter==='active'?!['Completed','Cancelled'].includes(x.status):x.status===filter)));
 const expenses=w.expenses.filter(x=>inPeriod(x.date)&&found(x.description,x.category)&&(filter==='void'?x.status==='void':x.status==='active'));
 const periodText=period==='all'?'All time':monthLabel(period);
 const chartData=useMemo(()=>{
  const keys=period==='all'?months.filter(m=>w.sales.some(x=>x.date.startsWith(m))||w.expenses.some(x=>x.date.startsWith(m))).sort():Array.from({length:new Date(Number(period.slice(0,4)),Number(period.slice(5)),0).getDate()},(_,n)=>period+'-'+String(n+1).padStart(2,'0'));
  return keys.map(key=>{const entries=w.sales.filter(x=>x.status==='active'&&x.date.startsWith(key)),exp=w.expenses.filter(x=>x.status==='active'&&x.date.startsWith(key)).reduce((a,x)=>a+x.amount,0);return {label:period==='all'?monthLabel(key).replace(/ \d+$/,''):String(Number(key.slice(-2))),sales:entries.reduce((a,x)=>a+x.total,0)/100,profit:(entries.reduce((a,x)=>a+x.total-x.cost,0)-exp)/100};});
 },[w,period,months]);
 function exportData(){
  const name='JBC-'+(demo?'SAMPLE-':'')+view+'-'+period+'.csv';
  if(view==='inventory')csvDownload(name,[['SKU','Item','Category','Quantity','Average cost PHP','Selling price PHP','Stock value PHP','Low-stock level'],...items.map(i=>[i.sku,i.name,i.category,i.stock,unitCost(i)/100,i.price/100,i.value/100,i.minimum])]);
  else if(view==='sales')csvDownload(name,[['Sale','Date','Customer','Total PHP','Direct cost PHP','Gross profit PHP','Paid PHP','Balance PHP','Status'],...sales.map(x=>[x.code,x.date,x.customer,x.total/100,x.cost/100,(x.total-x.cost)/100,x.paid/100,(x.total-x.paid)/100,paymentStatus(x)])]);
  else if(view==='expenses')csvDownload(name,[['Date','Description','Category','Amount PHP','Payment method','Status'],...expenses.map(x=>[x.date,x.description,x.category,x.amount/100,x.method,x.status])]);
  else if(view==='jobs')csvDownload(name,[['Customer','Contact','Device','Service','Received','Target','Quote PHP','Status','Notes'],...jobs.map(j=>[j.customer,j.contact,j.device,j.service,j.date,j.due,j.quote/100,j.status,j.notes])]);
  else csvDownload(name,[['JBC RIGWORKS',demo?'SAMPLE DATA':'Business report'],['Period',periodText],['Currency','PHP'],['Sales',s.revenue/100],['Direct costs',s.cost/100],['Gross profit',(s.revenue-s.cost)/100],['Operating expenses',s.expenses/100],['Net profit before tax',s.profit/100],['Cash collected',s.receipts/100],['Paid inventory purchases',s.purchases/100],['Service costs paid',s.serviceCost/100],['Cash operating expenses',s.cashExpenses/100],['Net recorded cash movement',s.cashFlow/100],['Outstanding balances - all time',s.receivables/100]]);
  toast.success('CSV downloaded');
 }
 const openReal=()=>{setDemo(false);setModal(null);setFilter('all');setSearch('');setPeriod(today().slice(0,7));};
 const SaleTable=({rows}:{rows:Sale[]})=>rows.length?<Table><TableHeader><TableRow><TableHead>Sale / customer</TableHead><TableHead>Service or product</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead><TableHead className="right">Amount</TableHead><TableHead className="right">Balance</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(x=><TableRow key={x.id}><TableCell><button className="table-link" onClick={()=>setModal({type:'detail',sale:x})}>{x.customer}</button><small>{x.code}</small></TableCell><TableCell><span className="truncate-cell">{x.lines[0]?.description}</span>{x.lines.length>1&&<small>+{x.lines.length-1} more item{x.lines.length>2?'s':''}</small>}</TableCell><TableCell>{dateLabel(x.date)}</TableCell><TableCell><Badge>{paymentStatus(x)}</Badge></TableCell><TableCell className="right amount">{money(x.total)}</TableCell><TableCell className="right">{x.status==='void'?'—':money(x.total-x.paid)}</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={'View '+x.code} onClick={()=>setModal({type:'detail',sale:x})}><ArrowUpRight size={17}/></Button></TableCell></TableRow>)}</TableBody></Table>:<Blank title="No sales here yet" description="Record a sale to see revenue, payments, and profit in one place." icon={ShoppingBag} action={<Button onClick={()=>setModal({type:'sale'})}><Plus size={16}/> Record a sale</Button>}/>;
 return <>
  <Sidebar className="business-sidebar"><SidebarHeader><div className="brand"><img src="/jbc-logo.jpeg" alt="JBC RIGWORKS — PC & Laptop Care Done Right"/></div><div className="workspace-label"><span className="workspace-square">J</span><div><b>Business Hub</b><small>JBC RIGWORKS</small></div><LockKeyhole size={14}/></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>WORKSPACE</SidebarGroupLabel><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>navigate(n.id)} className="nav-item"><n.icon/><span>{n.label}</span>{n.id==='jobs'&&activeJobs.length>0&&<b className="nav-count">{activeJobs.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><button className={'demo-toggle '+(demo?'selected':'')} onClick={()=>{setDemo(!demo);setFilter('all');setSearch('');setPeriod(today().slice(0,7));}}><FlaskConical size={17}/><span>{demo?'Return to real workspace':'Explore sample data'}</span><ArrowUpRight size={15}/></button><div className="sidebar-footer"><div className="avatar">JB</div><div><b>JBC workspace</b><small><LockKeyhole size={11}/> Private business records</small></div></div></SidebarFooter></Sidebar>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Workspace</span><ChevronRight size={14}/><b>{nav.find(n=>n.id===view)?.label}</b></div><div className="topbar-right"><span>PHP <i/> Philippine peso</span><Button variant="ghost" size="icon" aria-label="Refresh workspace" onClick={()=>void refresh()}><RefreshCw size={17}/></Button><span className="avatar small-avatar">JB</span></div></header>
   <main className="page-content">
    {demo&&<div className="demo-banner"><FlaskConical size={18}/><div><b>Sample workspace</b><span>Example figures only. Your business records stay separate.</span></div><Button variant="outline" size="sm" onClick={openReal}>Use my workspace <ArrowRight size={14}/></Button></div>}
    {loadError&&!demo&&<div role="alert" className="error-banner"><TriangleAlert size={18}/><span>{loadError}</span><Button variant="outline" onClick={()=>void refresh()}>Try again</Button></div>}
    <div className="page-heading"><div><p className="eyebrow">JBC RIGWORKS / BUSINESS HUB</p><h1>{pageCopy[view].title}</h1><p>{pageCopy[view].description}</p></div><div className="heading-actions">{!['jobs','inventory'].includes(view)&&<Choice label="Report period" value={period} onValueChange={setPeriod} options={[...months.map(m=>({value:m,label:monthLabel(m)})),{value:'all',label:'All time'}]}/>}{view==='overview'?<Button onClick={()=>setModal({type:'sale'})}><Plus size={17}/> New sale</Button>:<Button variant="outline" onClick={exportData}><Download size={16}/> Export CSV</Button>}</div></div>
    {loading&&!demo?<div className="metric-grid" aria-label="Loading workspace">{[0,1,2,3].map(i=><Skeleton key={i} className="h-36 rounded-xl"/>)}</div>:<>
    {(view==='overview'||view==='reports')&&<div className="metric-grid"><Metric title="Total sales" value={money(s.revenue,true)} note={s.sales.length+' sales · '+periodText} icon={ShoppingBag}/><Metric title="Costs & expenses" value={money(s.cost+s.expenses,true)} note="Direct costs + operating expenses" icon={ReceiptText}/><Metric title="Net profit" value={money(s.profit,true)} note={(s.revenue?s.margin.toFixed(1)+'% margin':'Before tax')+' · '+periodText} icon={TrendingUp} dark/><Metric title="To collect" value={money(s.receivables,true)} note="Outstanding balances · all time" icon={Wallet}/></div>}
    {view==='overview'&&<>
     {!demo&&!data.sales.length&&!data.items.length&&!loadError&&<div className="welcome-strip"><div><b>Your workspace is ready.</b><span>Start with your stock or record your first service sale.</span></div><Button variant="outline" onClick={()=>setModal({type:'item'})}><Plus size={15}/> Add inventory</Button><button className="text-button" onClick={()=>setDemo(true)}>View sample dashboard <ArrowRight size={15}/></button></div>}
     <div className="overview-grid"><Panel title="Sales & profit" subtitle={periodText} action={<div className="chart-legend"><span><i/>Sales</span><span><i/>Net profit</span></div>} className="chart-panel">{s.sales.length||s.expenses?<div className="chart" role="img" aria-label={'Daily sales and net profit for '+periodText+'. Total sales '+money(s.revenue)+', net profit '+money(s.profit)}><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{top:12,right:16,left:0,bottom:0}}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0867db" stopOpacity={0.17}/><stop offset="100%" stopColor="#0867db" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e8edf3" strokeDasharray="4 5"/><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={25} tick={{fill:'#718096',fontSize:12}}/><YAxis axisLine={false} tickLine={false} width={62} tickFormatter={v=>'₱'+(Math.abs(v)>=1000?(v/1000).toFixed(1)+'k':v)} tick={{fill:'#718096',fontSize:12}}/><Tooltip formatter={(v)=>money(Number(v)*100)} labelFormatter={v=>period==='all'?v:monthLabel(period)+' · '+v}/><Area name="Sales" type="monotone" dataKey="sales" stroke="#0867db" fill="url(#salesFill)" strokeWidth={2.5}/><Area name="Net profit" type="monotone" dataKey="profit" stroke="#13a795" fill="transparent" strokeWidth={2} strokeDasharray="4 3"/></AreaChart></ResponsiveContainer></div>:<Blank title="Your numbers start here" description="Your sales and expenses will turn into a daily profit view." icon={ChartNoAxesCombined}/>}<div className="chart-bottom"><span>Cash collected <b>{money(s.receipts)}</b></span><button className="text-button" onClick={()=>navigate('reports')}>View report <ArrowRight size={14}/></button></div></Panel>
     <Panel title="Workshop today" subtitle="Current service jobs" action={<Wrench size={18} className="muted"/>} className="workshop-panel"><div className="workshop-number"><strong>{activeJobs.length.toString().padStart(2,'0')}</strong><span>active jobs</span></div><div className="job-counts">{['Queued','In progress','Ready'].map(st=><div key={st}><span><i className={'stage-dot '+st.toLowerCase().replace(' ','-')}/>{st}</span><b>{w.jobs.filter(j=>j.status===st).length}</b></div>)}</div><Button variant="outline" className="full-button" onClick={()=>navigate('jobs')}>Open service jobs <ArrowRight size={15}/></Button></Panel></div>
     <div className="overview-lower"><Panel title="Recent sales" subtitle="Your latest transactions" action={<button className="text-button" onClick={()=>navigate('sales')}>View all <ArrowRight size={14}/></button>}><SaleTable rows={s.sales.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5)}/></Panel><Panel title="Stock to watch" subtitle={lowStock.length+' items at or below minimum'} action={<Package size={18} className="muted"/>}>{lowStock.length?<div className="stock-watch">{lowStock.slice(0,4).map(i=><button key={i.id} onClick={()=>setModal({type:'stock',item:i})}><span className="stock-icon"><Package size={19}/></span><span><b>{i.name}</b><small>{i.sku}</small></span><strong>{i.stock}<small>left</small></strong></button>)}</div>:<div className="compact-empty"><Check size={23}/><b>{w.items.length?'Stock levels look good':'No stock alerts yet'}</b><p>{w.items.length?'All items are above their minimum.':'Add your inventory to track low stock.'}</p></div>}<button className="panel-bottom-link" onClick={()=>{navigate('inventory');setFilter('low');}}>Manage inventory <ArrowRight size={14}/></button></Panel></div>
    </>}
    {view==='sales'&&<><div className="mini-stats"><span>Sales <b>{money(s.revenue)}</b></span><span>Collected this period <b>{money(s.receipts)}</b></span><span>Outstanding · all time <b>{money(s.receivables)}</b></span></div><div className="table-toolbar"><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="all">All sales</TabsTrigger><TabsTrigger value="paid">Paid</TabsTrigger><TabsTrigger value="unpaid">To collect</TabsTrigger><TabsTrigger value="void">Voided</TabsTrigger></TabsList></Tabs><div className="toolbar-actions"><div className="search-field"><Search size={16}/><Input aria-label="Search sales" placeholder="Search sales…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button onClick={()=>setModal({type:'sale'})}><Plus size={16}/> New sale</Button></div></div><div className="panel"><SaleTable rows={sales}/></div><p className="table-footnote">{sales.length} sale{sales.length===1?'':'s'} · {periodText}. Select a sale to view items or record a payment.</p></>}
    {view==='inventory'&&<><div className="mini-stats"><span>Stock value at cost <b>{money(w.items.reduce((v,i)=>v+i.value,0))}</b></span><span>Total units <b>{w.items.reduce((v,i)=>v+i.stock,0)}</b></span><span>Low-stock items <b>{lowStock.length}</b></span></div><div className="table-toolbar"><Tabs value={filter==='low'?'low':'all'} onValueChange={setFilter}><TabsList><TabsTrigger value="all">All inventory</TabsTrigger><TabsTrigger value="low">Low stock <span className="small-count">{lowStock.length}</span></TabsTrigger></TabsList></Tabs><div className="toolbar-actions"><div className="search-field"><Search size={16}/><Input aria-label="Search inventory" placeholder="Search inventory…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button onClick={()=>setModal({type:'item'})}><Plus size={16}/> Add item</Button></div></div><div className="panel">{items.length?<Table><TableHeader><TableRow><TableHead>Item / SKU</TableHead><TableHead>Category</TableHead><TableHead className="right">In stock</TableHead><TableHead>Status</TableHead><TableHead className="right">Avg. cost</TableHead><TableHead className="right">Sell price</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{items.map(i=><TableRow key={i.id}><TableCell><button className="table-link" onClick={()=>setModal({type:'item',item:i})}>{i.name}</button><small>{i.sku}</small></TableCell><TableCell>{i.category}</TableCell><TableCell className="right amount">{i.stock}<small>min. {i.minimum}</small></TableCell><TableCell><Badge>{i.stock===0?'Out of stock':i.stock<=i.minimum?'Low stock':'In stock'}</Badge></TableCell><TableCell className="right">{money(unitCost(i))}</TableCell><TableCell className="right amount">{money(i.price)}</TableCell><TableCell><div className="row-actions"><Button size="sm" variant="outline" onClick={()=>setModal({type:'stock',item:i})}><Plus size={14}/> Stock</Button><Button size="icon" variant="ghost" aria-label={'Edit '+i.name} onClick={()=>setModal({type:'item',item:i})}><SlidersHorizontal size={16}/></Button><Button size="icon" variant="ghost" aria-label={'Write off '+i.name} disabled={!i.stock} onClick={()=>setModal({type:'loss',item:i})}><Undo2 size={16}/></Button></div></TableCell></TableRow>)}</TableBody></Table>:<Blank title={search||filter==='low'?'No matching items':'Add your first stock item'} description="Track parts, accessories, and supplies with cost and stock levels." action={<Button onClick={()=>setModal({type:'item'})}><Plus size={16}/> Add item</Button>}/>}</div><p className="table-footnote">{items.length} items · Costs use weighted averages. Inventory purchases appear in cash flow; sold stock appears in profit.</p></>}
    {view==='expenses'&&<><div className="mini-stats"><span>Operating expenses <b>{money(s.expenses)}</b></span><span>Cash expenses <b>{money(s.cashExpenses)}</b></span><span>Period <b>{periodText}</b></span></div><div className="table-toolbar"><Tabs value={filter==='void'?'void':'all'} onValueChange={setFilter}><TabsList><TabsTrigger value="all">Recorded</TabsTrigger><TabsTrigger value="void">Voided</TabsTrigger></TabsList></Tabs><div className="toolbar-actions"><div className="search-field"><Search size={16}/><Input aria-label="Search expenses" placeholder="Search expenses…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button onClick={()=>setModal({type:'expense'})}><Plus size={16}/> Add expense</Button></div></div><div className="panel">{expenses.length?<Table><TableHeader><TableRow><TableHead>Description</TableHead><TableHead>Category</TableHead><TableHead>Date</TableHead><TableHead>Paid with</TableHead><TableHead className="right">Amount</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{expenses.map(x=><TableRow key={x.id}><TableCell className="amount">{x.description}</TableCell><TableCell>{x.category}</TableCell><TableCell>{dateLabel(x.date)}</TableCell><TableCell>{x.method}</TableCell><TableCell className="right amount">{money(x.amount)}</TableCell><TableCell>{x.status==='active'&&x.method!=='Non-cash'&&<Button variant="ghost" size="sm" onClick={()=>setConfirm({action:'expense.void',id:x.id,title:'Void this expense?',description:'This removes the expense from your reports. The original record stays in the Voided tab.'})}>Void</Button>}</TableCell></TableRow>)}</TableBody></Table>:<Blank title="No expenses in this view" description="Record paid costs such as supplies, utilities, rent, and marketing." icon={ReceiptText} action={<Button onClick={()=>setModal({type:'expense'})}><Plus size={16}/> Add expense</Button>}/>}</div></>}
    {view==='jobs'&&<><div className="mini-stats"><span>Active jobs <b>{activeJobs.length}</b></span><span>Ready for pickup <b>{w.jobs.filter(j=>j.status==='Ready').length}</b></span><span>Open quoted value <b>{money(activeJobs.reduce((v,j)=>v+j.quote,0))}</b></span></div><div className="table-toolbar"><Choice label="Job filter" value={filter} onValueChange={setFilter} options={[{value:'all',label:'All jobs'},{value:'active',label:'Active jobs'},...jobStatuses]}/><div className="toolbar-actions"><div className="search-field"><Search size={16}/><Input aria-label="Search jobs" placeholder="Search jobs…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button onClick={()=>setModal({type:'job'})}><Plus size={16}/> New job</Button></div></div>{jobs.length?<div className="jobs-grid">{jobs.map(j=>{const billed=w.sales.some(s=>s.job_id===j.id&&s.status==='active');return <article className="job-card" key={j.id}><div className="job-card-top"><span className="job-device-icon"><Wrench size={21}/></span><Badge>{j.status}</Badge></div><h2>{j.device}</h2><p className="job-service">{j.service}</p><div className="job-customer">{j.customer}{j.contact&&<small>{j.contact}</small>}</div>{j.notes&&<p className="job-notes">{j.notes}</p>}<div className="job-meta"><span>Target date<b className={j.due<today()&&!['Completed','Cancelled'].includes(j.status)?'overdue':''}>{dateLabel(j.due)}</b></span><span>Quote<b>{money(j.quote)}</b></span></div><div className="job-card-actions"><Button variant="outline" onClick={()=>setModal({type:'job',job:j})}>Update job</Button>{billed?<span className="billed"><Check size={14}/> Sale recorded</span>:j.status!=='Cancelled'&&<Button variant="ghost" onClick={()=>setModal({type:'sale',job:j})}>Create sale <ArrowRight size={14}/></Button>}</div></article>;})}</div>:<div className="panel"><Blank title="No service jobs here yet" description="Add a customer and device to start tracking the work." icon={Wrench} action={<Button onClick={()=>setModal({type:'job'})}><Plus size={16}/> New job</Button>}/></div>}</>}
    {view==='reports'&&<><div className="reports-grid"><Panel title="Profit & loss" subtitle={periodText}><div className="report-rows"><div><span>Sales revenue</span><b>{money(s.revenue)}</b></div><div><span>Direct costs of sales</span><b>− {money(s.cost)}</b></div><div className="subtotal"><span>Gross profit</span><b>{money(s.revenue-s.cost)}</b></div><div><span>Operating expenses</span><b>− {money(s.expenses)}</b></div><div className="report-total"><span>Net profit before tax</span><strong>{money(s.profit)}</strong></div></div><p className="report-note">Revenue is recognized on the sale date, including unpaid sales. Direct costs include sold stock and the service costs you enter.</p></Panel><Panel title="Recorded cash movement" subtitle={periodText}><div className="report-rows"><div><span>Customer payments received</span><b>{money(s.receipts)}</b></div><div><span>Stock purchases paid</span><b>− {money(s.purchases)}</b></div><div><span>Direct service costs paid</span><b>− {money(s.serviceCost)}</b></div><div><span>Operating expenses paid</span><b>− {money(s.cashExpenses)}</b></div><div className="report-total"><span>Net cash movement</span><strong>{money(s.cashFlow)}</strong></div></div><p className="report-note">Movement from recorded business transactions only. Opening cash, owner contributions, withdrawals, loans, and bank balances are not included.</p></Panel></div><div className="reports-grid"><Panel title="Sales by type" subtitle="What drives your revenue"><div className="breakdown">{['service','product'].map((kind,n)=>{const amount=s.sales.reduce((v,x)=>v+x.lines.filter(l=>l.kind===kind).reduce((a,l)=>a+l.price*l.quantity,0),0);return <div key={kind}><div><span>{kind==='service'?'Services':'Products'}</span><b>{money(amount)}</b></div><div className="bar-track"><i style={{width:(s.revenue?amount/s.revenue*100:0)+'%',background:n?'#13a795':'#0867db'}}/></div></div>;})}</div></Panel><Panel title="Expense breakdown" subtitle="Operating expenses by category"><div className="breakdown">{[...new Set(w.expenses.filter(e=>e.status==='active'&&inPeriod(e.date)).map(e=>e.category))].map(category=>{const amount=w.expenses.filter(e=>e.status==='active'&&inPeriod(e.date)&&e.category===category).reduce((v,e)=>v+e.amount,0);return <div key={category}><div><span>{category}</span><b>{money(amount)}</b></div><div className="bar-track"><i style={{width:(s.expenses?amount/s.expenses*100:0)+'%'}}/></div></div>;})}{!s.expenses&&<p className="muted">No operating expenses recorded in this period.</p>}</div></Panel></div><div className="report-method"><Coins size={20}/><div><b>How these figures work</b><p>Amounts are in Philippine pesos. Profit is before tax and includes the costs entered here. Stock uses a weighted average cost. Receivables show all unpaid active sales. These are internal business reports; tax calculations and official invoices are not included.</p></div></div></>}
    </>}
    <footer className="page-footer"><span>JBC RIGWORKS <i/> Business Hub</span><span>{demo?'Sample data · for exploration':'PHP · Asia/Manila'}</span></footer>
   </main>
  </div>
  <Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal(null);}}><DialogContent className={'hub-dialog '+(modal?.type==='sale'?'wide-dialog':'')}><DialogHeader><DialogTitle>{modal?.type==='sale'?'Record a sale':modal?.type==='stock'?'Add stock':modal?.type==='loss'?'Write off stock':modal?.type==='expense'?'Record an expense':modal?.type==='job'?(modal.job?'Update service job':'New service job'):modal?.type==='payment'?'Record a payment':modal?.type==='detail'?'Sale details':modal?.item?'Edit inventory item':'Add inventory item'}</DialogTitle><DialogDescription>{modal?.type==='detail'?modal.sale?.code:'JBC RIGWORKS · '+(demo?'Sample workspace':'Business workspace')}</DialogDescription></DialogHeader>{modal&&(modal.type==='detail'?<SaleDetail sale={w.sales.find(s=>s.id===modal.sale?.id)||modal.sale!} w={w} onPayment={sale=>setModal({type:'payment',sale})} onVoid={sale=>{setModal(null);setConfirm({action:'sale.void',id:sale.id,title:'Void this unpaid sale?',description:'This removes the sale from reports and returns its products to stock. The original entry stays in the Voided tab.'});}}/>:<RecordForm key={modal.type+(modal.item?.id||modal.job?.id||modal.sale?.id||'new')} modal={modal} w={w} save={save} demo={demo} exitDemo={openReal} close={()=>setModal(null)}/>)}</DialogContent></Dialog>
  <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open&&!busy)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{demo?'This is sample data. Open your real workspace to make changes.':confirm?.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy||demo} onClick={async e=>{e.preventDefault();if(!confirm)return;setBusy(true);try{await save({action:confirm.action,id:confirm.id},newId());setConfirm(null);}catch(e){toast.error(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}}>{busy?'Saving…':'Confirm void'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}

function SaleDetail({sale:s,w,onPayment,onVoid}:{sale:Sale;w:Workspace;onPayment:(s:Sale)=>void;onVoid:(s:Sale)=>void}){
 return <div className="sale-detail"><div className="detail-meta"><div><h3>{s.customer}</h3><p>{dateLabel(s.date)}</p></div><Badge>{paymentStatus(s)}</Badge></div><div className="detail-lines">{s.lines.map(l=><div key={l.id}><span><b>{l.description}</b><small>{l.quantity} × {money(l.price)}</small></span><strong>{money(l.quantity*l.price)}</strong></div>)}</div><div className="report-rows"><div><span>Total</span><b>{money(s.total)}</b></div><div><span>Direct costs</span><b>{money(s.cost)}</b></div><div><span>Gross profit</span><b>{money(s.total-s.cost)}</b></div><div><span>Paid</span><b>{money(s.paid)}</b></div><div className="report-total"><span>Balance due</span><strong>{s.status==='void'?'—':money(s.total-s.paid)}</strong></div></div>{s.notes&&<p className="detail-note">{s.notes}</p>}<h3 className="payment-history-title">Payment history</h3>{w.payments.filter(p=>p.sale_id===s.id).length?<div className="payment-history">{w.payments.filter(p=>p.sale_id===s.id).map(p=><div key={p.id}><span>{dateLabel(p.date)}<small>{p.method}</small></span><b>{money(p.amount)}</b></div>)}</div>:<p className="muted">No payments recorded.</p>}{s.status==='active'&&<div className="form-actions">{s.paid===0&&<Button variant="outline" onClick={()=>onVoid(s)}>Void unpaid sale</Button>}{s.paid<s.total&&<Button onClick={()=>onPayment(s)}><Plus size={16}/> Add payment</Button>}</div>}</div>;
}
