import { useState } from 'react'
import { FolderCog, Pencil, Plus, Save, Trash2, ReceiptText } from 'lucide-react'
import { PageHeader } from '../../components/ui/PageHeader'
import { Dialog } from '../../components/ui/Dialog'
import { ActionButton } from '../../components/ui/ActionButton'
import { directoryLabels, useDirectories, type DirectoryGroup, type FeePreset } from '../../lib/directories'
import { useShopSettings } from '../../lib/preferences'
export function DirectoriesPage() {
  const [data, save] = useDirectories(), [shop, saveShop] = useShopSettings()
  const [group, setGroup] = useState<DirectoryGroup | null>(null), [editing, setEditing] = useState<string | null>(null), [value, setValue] = useState(''), [error, setError] = useState('')
  const [feesOpen, setFeesOpen] = useState(false), [fee, setFee] = useState<FeePreset | null>(null)
  const [defaults, setDefaults] = useState({ taxRate: shop.taxRate, labor: shop.labor })
  function attempt(action: () => void) { try { action(); setError('') } catch (err) { setError((err as Error).message) } }
  function storeOption() { if (!group) return; const next = value.trim(); if (!next || data[group].some(item => item.toLowerCase() === next.toLowerCase() && item !== editing)) { setError('Enter a unique, nonempty value.'); return } attempt(() => { save({ ...data, [group]: editing ? data[group].map(item => item === editing ? next : item) : [...data[group], next] }); setValue(''); setEditing(null) }) }
  return <><PageHeader eyebrow="WORKSPACE DIRECTORY" title="Directories" description="Manage choices used by forms. Existing records keep their original values." />
  <div className="settings-menu">{(Object.keys(directoryLabels) as DirectoryGroup[]).map(key => <button className="settings-tile" key={key} onClick={() => { setGroup(key); setEditing(null); setValue(''); setError('') }}><FolderCog size={25}/><span><strong>{directoryLabels[key]}</strong><small>{data[key].length} values</small></span></button>)}<button className="settings-tile" onClick={() => { setFeesOpen(true); setDefaults({ taxRate: shop.taxRate, labor: shop.labor }); setError('') }}><ReceiptText size={25}/><span><strong>VAT, fees & deductions</strong><small>Defaults and reusable checkout presets</small></span></button></div>
  <p className="storage-caption">Part models, stock quantities, and tiers are maintained in Inventory. Component types and transaction statuses are fixed workflow categories.</p>
  {group && <Dialog title={directoryLabels[group]} onClose={() => setGroup(null)}><div className="directory-values">{data[group].map(item => <div className="directory-row" key={item}><span>{item}</span><ActionButton label={'Edit ' + item} onClick={() => { setEditing(item); setValue(item) }}><Pencil size={17}/></ActionButton><ActionButton label={'Delete ' + item} onClick={() => { if (data[group].length < 2) { setError('Keep at least one value in this directory.'); return } if (window.confirm('Delete this option from future forms?')) attempt(() => save({ ...data, [group]: data[group].filter(value => value !== item) })) }}><Trash2 size={17}/></ActionButton></div>)}</div><form className="portal-form settings-fields" onSubmit={e => { e.preventDefault(); storeOption() }}><label>{editing ? 'Edit value' : 'New value'}<input required maxLength={100} value={value} onChange={e => setValue(e.target.value)}/></label><div className="dialog-actions"><ActionButton type="submit" label={editing ? 'Save value' : 'Add value'}><Save size={19}/></ActionButton>{editing && <ActionButton label="New value" onClick={() => { setEditing(null); setValue('') }}><Plus size={19}/></ActionButton>}</div></form>{error && <p role="alert" className="form-error">{error}</p>}</Dialog>}
  {feesOpen && <Dialog title="VAT, fees & deductions" onClose={() => setFeesOpen(false)}><form className="portal-form settings-fields" onSubmit={e => { e.preventDefault(); attempt(() => { if (!Number.isFinite(defaults.taxRate) || defaults.taxRate < 0 || defaults.taxRate > 100 || !Number.isFinite(defaults.labor) || defaults.labor < 0) throw new Error('Check the default amounts.'); saveShop({ ...shop, ...defaults }); setFeesOpen(false) }) }}><div className="portal-form-grid"><label>Default VAT / tax (%)<input type="number" min="0" max="100" step="0.01" value={defaults.taxRate} onChange={e => setDefaults({ ...defaults, taxRate: Number(e.target.value) })}/></label><label>Default labor (PHP)<input type="number" min="0" step="0.01" value={defaults.labor} onChange={e => setDefaults({ ...defaults, labor: Number(e.target.value) })}/></label></div><ActionButton type="submit" label="Save fee defaults"><Save size={19}/></ActionButton></form><h3>Checkout presets</h3><div className="directory-values">{data.fees.map(item => <div className="directory-row" key={item.id}><span>{item.name}<small>{item.kind} / {item.value}{item.kind === 'taxRate' ? '%' : ' PHP'}</small></span><ActionButton label={'Edit ' + item.name} onClick={() => setFee(item)}><Pencil size={17}/></ActionButton><ActionButton label={'Delete ' + item.name} onClick={() => { if (window.confirm('Delete this fee preset?')) attempt(() => save({ ...data, fees: data.fees.filter(value => value.id !== item.id) })) }}><Trash2 size={17}/></ActionButton></div>)}</div><ActionButton label="Add fee preset" onClick={() => { setFee({ id: crypto.randomUUID(), name: '', kind: 'other', value: 0 }); setError('') }}><Plus size={20}/></ActionButton>{error && <p role="alert" className="form-error">{error}</p>}</Dialog>}
  {fee && <Dialog title="Fee preset" onClose={() => setFee(null)}><form className="portal-form settings-fields" onSubmit={e => { e.preventDefault(); attempt(() => { if (!fee.name.trim() || !Number.isFinite(fee.value) || fee.value < 0 || (fee.kind === 'taxRate' && fee.value > 100)) throw new Error('Enter a name and valid amount.'); save({ ...data, fees: [...data.fees.filter(item => item.id !== fee.id), { ...fee, name: fee.name.trim() }] }); setFee(null) }) }}><label>Preset name<input required maxLength={100} value={fee.name} onChange={e => setFee({ ...fee, name: e.target.value })}/></label><label>Type<select value={fee.kind} onChange={e => setFee({ ...fee, kind: e.target.value as FeePreset['kind'] })}><option value="taxRate">VAT / tax percentage</option><option value="labor">Labor charge</option><option value="other">Other fee</option><option value="discount">Deduction</option></select></label><label>Amount or percentage<input required type="number" min="0" step="0.01" max={fee.kind === 'taxRate' ? 100 : undefined} value={fee.value} onChange={e => setFee({ ...fee, value: Number(e.target.value) })}/></label>{error && <p role="alert" className="form-error">{error}</p>}<ActionButton type="submit" label="Save fee preset"><Save size={19}/></ActionButton></form></Dialog>}</>
}
